import json
from pathlib import Path
R=Path('.')
DATA=[]
def skill(id,title,category,description,steps,boundary,example,refs,tags):
    DATA.append(dict(id=id,title=title,category=category,description=description,steps=steps,boundary=boundary,example=example,refs=refs,tags=tags))

skill('typescript-7-adoption','TypeScript 7 Adoption','TypeScript','Qualify a repository for native TypeScript 7 with a compatibility matrix, separate compiler-API consumers, diagnostic parity, measured performance, and reversible adoption.',[
'Inventory actual compiler commands, package locks, tsconfig inheritance, editor integration, build scripts, CI, and tools importing the TypeScript compiler API. Record which executable each path invokes; a version file alone is not runtime evidence.',
'Check official release notes for the exact candidate version. TypeScript 7.0 ships a native compiler without the previous compiler API. Retain a deliberately pinned TypeScript 6 path for integrations that require it. Name its owner and retirement condition instead of making two ambiguous global tsc commands.',
'In an owned branch, compare baseline and candidate diagnostics, declaration output, module resolution, project references, and relevant editor behavior on identical source. Replace removed configuration options deliberately; do not suppress errors wholesale or equate transpilation with checking.',
'Exercise Node ESM packages, browser-bundled packages, generated consumers, and compiler-API integrations independently. Test emitted packages from a disposable external consumer, not only workspace aliases. Keep unsupported integrations as explicit bounded blockers.',
'Measure repeated cold and warm runs with the same workload and hardware. Report wall time, observable memory, diagnostic parity, and aggregate concurrency. Reserve capacity for other lanes. Adopt only qualified paths and retain a tested baseline rollback.'
], 'A framework plugin imports the classic compiler API: preserve a scoped compatibility route rather than forcing a native compiler into that API slot.', 'An SDK can qualify native checks while an Astro documentation site retains its compatible toolchain. An unrelated Go service is outside this compiler migration.', [('TypeScript 7.0 release','https://devblogs.microsoft.com/typescript/announcing-typescript-7-0/'),('Nx TypeScript 7','https://nx.dev/docs/kb/typescript-7')], ['typescript','typescript 7','native compiler','migration'])

skill('typescript-type-design','TypeScript Type Design','TypeScript','Design domain types and runtime input boundaries that distinguish legal states, optional values, and exhaustive transitions without unsafe assertions.',[
'Find actual input boundaries: HTTP, storage, environment, jobs, or plugins. Treat unvalidated external values as unknown. State which validation permits constructing trusted domain values; compile-time types do not validate JSON.',
'Model dependent fields with a discriminated union rather than an optional-field bag. Specify missing versus undefined versus null semantics. Use branded identifiers only with controlled constructors and validation.',
'Keep exported types deliberate and local inference simple. Prefer inspectable types over unbounded generic machinery. Choose literal unions, enums, or runtime objects for their actual runtime/packaging needs rather than assuming one is universally superior.',
'Add compile-time negative fixtures and exhaustive handlers. Exercise runtime validators with malformed input, null/absent fields, unknown versions, enum additions, numeric limits, serialization, and documented errors. Expected behavior comes from the accepted contract, not the implementation alone.',
'Review emitted declarations and supported consumers. Specify whether unknown fields are rejected or preserved. Do not widen public contracts or use any/double assertions merely to make a failing check pass.'
], 'An API adds an enum value that an old client receives: use the documented unknown-value policy; local exhaustive types do not validate future wire values.', 'Represent a job as queued, running, succeeded with an asset, or failed with an error. Validate external job data before creating the corresponding union member.', [('TypeScript narrowing','https://www.typescriptlang.org/docs/handbook/2/narrowing.html')], ['typescript','types','validation','state machines'])

skill('typescript-esm-packages','TypeScript ESM Packages','TypeScript','Build ESM package boundaries against real Node/browser consumers, export maps, declaration files, and initialization behavior instead of workspace-only imports.',[
'Read package type, module/moduleResolution settings, extensions, export conditions, and the actual runtime. Match Node-targeted resolution to Node and bundled resolution to the bundler. TypeScript path aliases do not automatically create runtime aliases.',
'Define supported entry points and declarations. Keep internal files private through an explicit export map. Check emitted JavaScript extensions and imports. Add CommonJS output only for an actual supported consumer and test that output separately.',
'Inspect import-time side effects, environment access, server dependencies in browser entry points, and dependencies exposed by declarations. Use type-only imports where appropriate. Importing a library must not silently launch workers or open a database.',
'Create a local package archive using the repository package manager. Exercise it in disposable consumers without publishing to a registry. Test public subpaths, types, and intentional private-subpath rejection against the packed artifact.',
'Reconcile editor, tests, and production imports. Distinguish missing build output, invalid exports, extension mismatch, and unsupported runtime. Do not make all internals public to hide a resolution failure.'
], 'A downstream consumer requires CommonJS: record and test a deliberate compatibility route rather than claiming ESM is automatically sufficient.', 'An SDK source alias works inside the monorepo but fails outside it. A consumer of the packed artifact tests the corrected public JavaScript and declaration entry points.', [('Node packages','https://nodejs.org/api/packages.html'),('TypeScript modules','https://www.typescriptlang.org/docs/handbook/modules/reference.html')], ['typescript','esm','node','sdk','exports'])

skill('typescript-native-quality','TypeScript Native Quality Checks','TypeScript','Compose native compiler diagnostics, formatting, linting, type-aware analysis, and runtime tests as distinct checks with precise task inputs and actual evidence.',[
'Map current commands to formatting, style/syntax linting, type-aware linting, compiler diagnostics, runtime testing, and emitting builds. Running tsx or a bundler is not a full typecheck. Reuse selected tools rather than installing an overlapping stack.',
'Qualify the pinned TypeScript, Oxlint, optional type-aware service, and task-runner combination. Verify required rules and compiler-API consumers. Keep experimental integrations optional until positive and negative fixtures establish the required behavior.',
'Include inherited config, rule files, generator outputs, relevant environment inputs, tool versions, and dependency outputs in task identity. Give concurrent lanes private mutable compiler/build state. Focused selection does not replace mandatory integration gates.',
'Separate authorized fix mode from verification. Formatting may change owned files; verification should report drift without editing unrelated files. Re-run relevant checks after a tool modifies source because earlier results describe the previous state.',
'Seed a formatting violation, forbidden import, type error, and runtime defect in suitable disposable fixtures. Record which gate detects each and that valid fixtures pass. Preserve unsupported-capability and skipped-check labels instead of presenting a blanket pass.'
], 'A formatter edits source after tests pass: invalidate the earlier state-specific evidence and rerun the relevant checks.', 'Formatting passes while a regenerated SDK fails type checking. Report each result independently rather than treating the native toolchain as one interchangeable check.', [('Oxlint type-aware checks','https://oxc.rs/docs/guide/usage/linter/type-aware'),('Nx inputs','https://nx.dev/docs/reference/inputs')], ['typescript','typescript 7','oxlint','oxfmt','typecheck'])

skill('go-service-boundaries','Go Service Boundaries','Go','Implement cohesive Go packages with thin transports, explicit dependency and transaction ownership, and shared application policy across API, CLI, and MCP entry points.',[
'Trace the actual feature through go.mod, imports, handlers, application behavior, and persistence. Distinguish files, Go compilation packages, and deployable services. Keep unrelated restructuring out of the task.',
'Group behavior that changes together and use internal packages where appropriate. Place interfaces near their consumers when a real substitution boundary warrants them. Avoid global miscellaneous/interfaces packages and tiny forwarding packages.',
'Keep HTTP, CLI, and MCP adapters responsible for transport validation, trusted identity construction, use-case calls, and outcome translation. Business rules and authorization should converge on shared application behavior.',
'Pass dependencies explicitly instead of using package globals. Propagate context and assign owners for transactions, goroutines, and cleanup. Avoid hidden commits in low-level repositories and background work started at import time.',
'Test use-case behavior separately from transport mapping, then exercise a representative transport-to-storage path. Preserve useful error identity through errors.Is/errors.As where appropriate while redacting sensitive public details. Run the actual package and boundary checks.'
], 'Package extraction creates an import cycle: fix responsibility ownership rather than creating a service or miscellaneous type package solely to silence the compiler.', 'HTTP and an agent tool create a reservation through one use case that owns its transaction; adapters translate the same domain conflict into their documented transport errors.', [('Go module layout','https://go.dev/doc/modules/layout'),('Go errors','https://pkg.go.dev/errors')], ['go','golang','architecture','http','mcp'])

skill('go-concurrency-cancellation','Go Concurrency and Cancellation','Go','Implement bounded Go concurrency with clear goroutine lifetimes, cancellation, backpressure, channel ownership, and verified shutdown/error behavior.',[
'Name who starts each goroutine, waits for it, cancels it, and closes each channel. Specify queue capacity and maximum concurrent effects. An unbounded goroutine count is not a resource budget.',
'Propagate the caller context through blocking operations. Use context-aware APIs and cancellation-aware sends/receives where needed. Cancel derived contexts. Do not discard inherited deadlines by switching to a background context.',
'Define partial-result and failure semantics: cancel peers, collect all results, or retain completed work. Keep channel closure with the producing owner and prevent cancelled consumers from stranding blocked producers.',
'Bound worker pools to CPU, database, or provider constraints. Stop admission before draining/cancelling and join owned goroutines as required. A cancellation request does not prove an external operation stopped or undid its effects.',
'Test slow producers, early consumer exits, full queues, partial failure, deadline expiry, and repeated shutdown. Use controlled in-process schedules where supported plus race detection on exercised paths. Keep real dependency tests for the integration boundary.'
], 'A provider completes after local cancellation: reconcile that outcome rather than assuming cancellation reversed the effect.', 'Four thumbnail calls may be active. Cancellation stops admission and signals cooperative work; the caller joins owned workers rather than leaving an unlimited retry loop.', [('Go context','https://pkg.go.dev/context'),('Go race detector','https://go.dev/doc/articles/race_detector')], ['go','concurrency','cancellation','workers','backpressure'])

skill('go-testing-determinism','Go Deterministic Testing','Go','Design Go tests with independent assertions, controlled in-process timing, bounded fuzz/race checks, and isolated real dependencies for persistence and network semantics.',[
'Derive expected behavior from accepted requirements. Use meaningful input partitions and check both results and prohibited state changes. Give fixtures isolated state and explicit cleanup ownership.',
'Qualify testing/synctest or another supported timing strategy against the pinned Go version. Its fake clock and bubble do not simulate real database or network operations. Prefer event coordination to arbitrary sleeps and bound real external waits.',
'Prove regression detection against a known defective fixture when practical. A compiler error or missing service is not the intended assertion failure. Keep any deliberate mutation small, controlled, and confined to disposable work.',
'Separate unit, race-detector, bounded fuzzing, and integration scopes. Preserve meaningful fuzz failures. Do not mock the exact transaction or serialization boundary whose correctness the test is supposed to establish.',
'Record cache reuse and attempts. Use go test -count=1 when a trial requires fresh execution, not as a universal cache disable. Repeat timing-sensitive cases and report failures instead of rerunning until one pass appears.'
], 'The test depends on a real PostgreSQL response: do not claim fake-clock unit coverage proves its integration behavior.', 'Check a lease immediately before, at, and after expiry using the specified inclusivity rule; a separate real database test verifies rejected renewal leaves stored state unchanged.', [('Go synctest','https://pkg.go.dev/testing/synctest'),('Go testing','https://pkg.go.dev/testing'),('Go fuzzing','https://go.dev/doc/security/fuzz/')], ['go','testing','synctest','fuzz','race detector'])

skill('go-performance-profiling','Go Performance Profiling','Go','Investigate Go latency, CPU, allocation, and contention bottlenecks using representative profiles, controlled benchmarks, and correctness-preserving changes.',[
'Define the user-visible target: latency, throughput, allocation, startup, or resource use. Include queue and dependency time for an end-to-end claim. Record workload, concurrency, warm state, tools, hardware, and limits.',
'Collect baseline profiles appropriate to the symptom: CPU, heap/allocation, blocking, mutex, or trace. Use authorized environments and protect sensitive profiles and diagnostics endpoints.',
'Rank causes from evidence rather than code appearance. Separate computation, lock contention, allocation, database delay, and serialization. Check whether more parallelism increases total resource contention.',
'Change one meaningful factor while preserving behavior tests. Re-run equivalent measurements and retain the baseline. Pooling, caching, and batching require correct bounds, lifetime, and invalidation rules.',
'Repeat measurements and report sample counts and spread. Include memory, latency, correctness, and affected workloads that regress. A microbenchmark improvement is not an application-wide speed multiplier.'
], 'A faster microbenchmark doubles peak memory: report both and judge against the predeclared acceptance target.', 'Most endpoint time is spent waiting for a serialized database operation. Investigate that transaction path rather than rewriting a small JSON helper.', [('Go diagnostics','https://go.dev/doc/diagnostics'),('Go benchmarks','https://pkg.go.dev/testing')], ['go','pprof','profiling','performance','benchmarks'])

skill('openapi-contract-evolution','OpenAPI Contract Evolution','Contracts','Evolve OpenAPI contracts against an accepted consumer baseline with explicit wire semantics, compatibility analysis, migration decisions, and runtime checks.',[
'Locate the authoritative modular specifications and their owner/generation chain. Record accepted or released baseline and candidate revisions; an arbitrary moving branch is not automatically a customer-compatibility baseline.',
'Specify required/optional properties, nullability, numeric bounds, enum extensions, errors, pagination, authentication, and idempotency where relevant. Separate schema facts from business invariants that the schema cannot express.',
'Use the configured compatibility checker, such as qualified oasdiff, to inspect removals, tightened constraints, response changes, and generator-facing operation IDs. Verify seeded compatible and incompatible fixtures.',
'For intentional breaks, document versioning or migration and overlapping consumer/server deployments. Generate with pinned tools and test supported old consumers as well as new ones; compilation of the new client alone is insufficient.',
'Exercise bounded malformed/boundary requests and real response behavior against a disposable service. Maintain independent authorization, tenant, and effect assertions. Do not change the accepted baseline to hide a break.'
], 'Schema tests pass but a tenant receives another tenant’s object: fail the independent access invariant instead of calling the API correct.', 'An optional field becomes required. A new client compiles, but an old server may omit it; check deployment order and both wire directions.', [('OpenAPI 3.1.1','https://spec.openapis.org/oas/v3.1.1.html'),('oasdiff','https://www.oasdiff.com/'),('Schemathesis','https://schemathesis.readthedocs.io/en/stable/')], ['openapi','api','contracts','compatibility','oasdiff'])

skill('generated-client-integrity','Generated Client Integrity','Contracts','Keep generated Go and TypeScript clients, validators, and queries aligned with canonical inputs using pinned generation, reproducible output, and real consumer/wire tests.',[
'Map canonical source through generator/version/configuration to emitted files and actual consumers. Identify committed versus ignored outputs and non-file inputs. Consumers must depend on what they actually read.',
'Edit canonical specifications, queries, or generation configuration instead of patching generated files. Keep custom adapters outside generated directories and fail on output drift rather than maintaining two hand-edited sources.',
'Generate in an owned directory, repeat, and compare output identities. Normalize only documented irrelevant variability. Identical generated output permits downstream reuse only where graph declarations support that dependency model.',
'Compile Go and TypeScript consumers and exercise serialization/runtime validation. Include absent/null values, large IDs, enum extensions, timestamps, and errors. Generating a validator does not mean requests and responses actually use it.',
'Assign one writer to shared schemas/outputs and give downstream lanes stable contract/output identities. Report unavailable generators as blocked; do not fabricate generated code or hand-author dependency locks.'
], 'Consumed generated files are ignored by Git: prove downstream invalidation follows their content rather than relying on git diff alone.', 'A generated integer type agrees in Go and TypeScript but exceeds JavaScript exact precision. Add a deliberate wire representation and cross-language round-trip fixtures.', [('oapi-codegen','https://github.com/oapi-codegen/oapi-codegen'),('Hey API Valibot','https://heyapi.dev/docs/openapi/typescript/plugins/valibot'),('sqlc','https://docs.sqlc.dev/en/latest/howto/transactions.html')], ['openapi','codegen','go','typescript','valibot','sqlc'])

skill('postgres-transaction-boundaries','PostgreSQL Transaction Boundaries','Data','Implement database invariants with explicit transaction ownership, isolation decisions, constraint-backed concurrency control, and retry-safe effects.',[
'State the invariant across relevant rows and concurrent requests. Separate authoritative database state from caches. A single-request pass is not evidence for a concurrent invariant.',
'Assign transaction begin/commit/rollback to the use-case owner. Pass transaction-bound query adapters through lower layers; qualify sqlc WithTx with the actual pgx/database integration. Avoid hidden commits in helpers.',
'Choose constraints, conditional writes, row locks, or serializable execution according to the invariant. Record isolation behavior, lock ordering, conflicts, and retries. An unchecked read-then-write can admit competing writers.',
'Keep external effects outside ambiguous transaction retries through an accepted intent/outbox or other coordination strategy. Retrying a serialization failure must rebuild the transaction’s decisions, not only replay its final SQL statement.',
'Use a real disposable PostgreSQL fixture for isolation/constraints. Coordinate overlapping transactions and assert final state, results, and prohibited effects. Exercise rollback, cancellation, and retry exhaustion with private writable resources per lane.'
], 'An external effect completed before a transaction retry: prevent repeating it through durable coordination rather than claiming database atomicity covers the provider.', 'Two requests compete for the final slot; require exactly one reservation, nonnegative capacity, and no duplicate notification intent.', [('PostgreSQL isolation','https://www.postgresql.org/docs/current/transaction-iso.html'),('sqlc transactions','https://docs.sqlc.dev/en/latest/howto/transactions.html')], ['postgresql','pgx','sqlc','transactions','concurrency'])

skill('postgres-migration-safety','PostgreSQL Migration Safety','Data','Test schema changes against populated prior versions, rolling application compatibility, locks/backfills, and explicit recovery rather than clean-install success alone.',[
'Read the actual migration runner, ordering, applied-version tracking, and transaction mode. Separate upward/downward sections as executed. Identify supported starting schemas instead of assuming an empty database.',
'Assess table size, locks, indexes, defaults, constraints, and old/new readers and writers. Use staged expand/backfill/contract where necessary. Make large backfills bounded and resumable with one accountable owner.',
'Lint the SQL that actually executes with the selected PostgreSQL/transaction settings. Qualify configured tools such as Squawk using risky and valid fixtures. Static linting is not a measurement of production lock duration.',
'Test fresh installation and populated upgrades with representative synthetic data. Assert preservation, constraints, application behavior, and resume/repeat semantics. Snapshot identity includes version, extensions, migrations, and data; restore only inactive owned resources.',
'Define rollback versus forward repair before rollout. Test overlapping application versions and explicitly approve compatibility removal. Do not run production migrations or broad destructive restores just to finish a review.'
], 'Another lane is using the database selected for restore: wait or allocate separate owned resources rather than reset shared active state.', 'An optional column becomes required through compatible writes, a backfill, and later enforcement; verify a populated upgrade and both old/new writers.', [('Squawk','https://squawkhq.com/docs/'),('PostgreSQL test snapshots','https://golang.testcontainers.org/modules/postgres/'),('ALTER TABLE','https://www.postgresql.org/docs/current/sql-altertable.html')], ['postgresql','migrations','squawk','backfill','testcontainers'])

skill('temporal-workflow-determinism','Temporal Workflow Determinism','Durable workflows','Evolve deterministic orchestration using representative history replay, version-qualified SDK behavior, and separate tests for external activity effects.',[
'Trace workflow calls and separate network, filesystem, database, and provider effects into activities or appropriate supported SDK mechanisms. Use the installed SDK’s deterministic workflow time/concurrency APIs.',
'Specify timers, signals/updates, cancellation, compensation, retry decisions, terminal states, and history growth. Keep payloads bounded; asset bytes should use suitable storage and durable references instead of oversized workflow arguments.',
'Review command-sequence changes against running executions. Qualify version markers, deployment pinning, or supported evolution methods for the actual SDK/server. A refactor is not automatically replay-neutral.',
'Replay a synthetic or sanitized corpus covering meaningful waiting, cancellation, retry, compensation, and completion states. Record history identities and include a deliberately incompatible fixture to prove the replay gate detects the intended failure.',
'Test activities and effects separately. Replay does not execute providers, prove idempotency, or preserve database compatibility. Coordinate workflow, worker, API, and schema transitions before release.'
], 'History replay passes but an activity can double-charge on retry: keep the effect invariant unresolved and test it separately.', 'Adding an activity before a timer can change command history. Test representative old histories and an accepted evolution strategy rather than relying on compilation.', [('Temporal Go replay','https://docs.temporal.io/develop/go/best-practices/testing-suite'),('Workflow versioning','https://docs.temporal.io/develop/go/workflows/versioning')], ['temporal','go','workflow','replay','determinism'])

skill('temporal-activity-idempotency','Temporal Activity Idempotency','Durable workflows','Design retryable effects with stable business identities, bounded timeouts, durable reconciliation, and tests for success before acknowledgment failure.',[
'Identify the business effect that must not repeat and distinguish it from activity attempt IDs. Decide what may repeat safely and what requires deduplication or reconciliation. Retries do not provide an exactly-once guarantee.',
'Carry a stable accepted-operation key across attempts rather than generating a new one each time. Reject incompatible key reuse and qualify the provider’s actual scope, expiry, and replay semantics.',
'Bound timeout, retry, concurrency, heartbeat, and cancellation behavior to the actual operation. Cancelling a local wait does not necessarily cancel a remote job. Avoid overlapping retries creating uncontrolled effects.',
'Plan for provider success followed by timeout/crash before acknowledgment. Check durable state or provider status before repeating a non-idempotent action. When reconciliation is impossible, expose indeterminate status and a reviewed recovery path.',
'Complete the effect in a disposable fixture, fail before acknowledgment, and retry. Assert effect counts and stored results. Also test duplicate delivery, payload changes with reused keys, cancellation, and exhaustion without paid production calls.'
], 'The provider’s idempotency retention expires before retry: use durable reconciliation or an indeterminate outcome rather than blindly resubmit.', 'An export was accepted but the activity lost its response. Retry reconciles the existing export using the same business identity instead of creating and billing another one.', [('Temporal failure handling','https://docs.temporal.io/develop/go/failure-detection'),('Provider idempotency example','https://docs.stripe.com/api/idempotent_requests')], ['temporal','activities','idempotency','retries','providers'])

skill('temporal-worker-rollout','Temporal Worker Rollout','Durable workflows','Qualify worker upgrades against self-hosted prerequisites, actual execution routing, replay evidence, external compatibility, and safe version drainage.',[
'Inventory installed server/SDK versions and check the intended Worker Versioning APIs and prerequisites. Do not silently upgrade a self-hosted server to make a recipe usable.',
'Define which version receives new work and which versions continue existing executions. Specify workflow types, queues, activity placement, and drain criteria; a version label alone does not establish routing.',
'Run replay and relevant worker tests and ensure old workers remain compatible with new schemas/APIs. Preserve needed old artifacts/configuration for the required lifetime; pinning execution does not freeze external dependencies.',
'In nonproduction, start representative long-running executions on the old version, introduce the candidate, and observe routing and completion. Test supported ramp reduction, recovery, cancellation, and rollback using actual visibility evidence.',
'Remove old workers only after supported visibility and status checks demonstrate they are no longer required. Coordinate retention and external compatibility retirement; do not kill them merely because new replicas are healthy.'
], 'An old pinned worker requires a database column removed by the rollout: reject the plan until that cross-system dependency is resolved.', 'Hours-long export workflows remain on a supported old route while new executions enter the candidate; schema compatibility persists until the old executions drain.', [('Temporal Worker Versioning','https://docs.temporal.io/worker-versioning')], ['temporal','workers','rollout','self-hosted','draining'])

skill('nx-graph-and-boundaries','Nx Graph and Boundaries','Parallel engineering','Use current project/task graphs and semantic navigation to map impact, enforce important boundaries, and validate derived configuration without duplicating existing tooling.',[
'Confirm the CLI, agent, MCP server, and language server resolve the same actual worktree and candidate files. Read existing configuration before generating or installing integrations.',
'Use project graphs for dependency structure, task graphs for execution order, and language services for symbols/types. Do not infer deployable ownership or all business dependencies solely from imports.',
'Start with a few actionable rules such as client/server adapter separation. Qualify the enforcement version and language coverage; TypeScript import checks do not automatically enforce Go architecture.',
'Where sync generators are configured, introduce derived drift in a disposable fixture, detect it, generate the correction, and confirm the next run is unchanged. Keep substantial code generation explicit.',
'Test allowed/forbidden edges and representative source, contract, and configuration changes. Record selection and check results. Missing graph edges are correctness defects; making every task depend on everything is not precision.'
], 'A graph server points to main while a child edits a worktree: fix the binding or mark the data stale instead of using it as candidate evidence.', 'Reject a client import of a server adapter while allowing shared contracts; qualify a separate appropriate check for Go package boundaries.', [('Nx graph exploration','https://nx.dev/docs/features/explore-graph'),('Nx boundaries','https://nx.dev/docs/features/enforce-module-boundaries'),('gopls','https://go.dev/gopls/features/')], ['nx','graphs','module boundaries','gopls','worktrees'])

skill('cache-invalidation-testing','Cache Invalidation Testing','Parallel engineering','Verify cache reuse with controlled input mutations and fresh reference execution, including generated and ignored outputs, environment, and toolchain changes.',[
'Separate affected selection, task-result reuse, compiler caches, container caches, and runtime-data caches. A selected task may reuse a valid result; a matching key still does not establish producer trust.',
'Create a disposable baseline with source, generator, configuration, toolchain, environment, and fixture identity. Declare expected task invalidation before observing results. Do not delete canonical source or application state to simulate a cold build.',
'Mutate meaningful source, test, unrelated documentation, contract, generated/ignored output, environment, and tool-version inputs one at a time. Include a deliberately omitted dependency that must expose stale reuse.',
'Record selection, cache decisions, restored artifacts, and a fresh reference result. Compare meaningful output/behavior rather than hit rates alone. Normalize only documented irrelevant variability and use focused key diagnostics instead of clearing every cache.',
'Correct the narrow missing relationship and rerun the matrix. Identical generated output may preserve consumer reuse where explicitly supported. Report false misses separately from false hits and keep remote-cache publication isolated.'
], 'A cache hits after consumed ignored output changed: prove whether it is stale and correct the actual missing dependency.', 'Ignored generated validators change while git diff is empty; consumers must revalidate. A no-op generation should not invalidate unrelated applications.', [('Nx inputs','https://nx.dev/docs/reference/inputs'),('Go cache commands','https://pkg.go.dev/cmd/go')], ['cache','invalidation','nx','generated output','warming'])

skill('build-cache-trust','Build Cache Trust','Infrastructure','Review producer/consumer cache authority, scoped credentials, sensitive output, nonproduction denial tests, and recovery from suspect artifacts.',[
'Map read, write, overwrite, and deletion authority by public contribution, branch CI, protected integration, and release identity. Consider first-writer poisoning as well as replacement of existing keys.',
'Check the exact maintained cache implementation and installed package status, including Nx self-hosted cache deprecation where relevant. A branch name or directory prefix is not authorization.',
'Separate untrusted writes from release-trusted publication with enforceable permissions. Review whether cache reads expose private output. Scope BuildKit exports so competing writers do not unexpectedly replace one mutable reference.',
'Use a disposable cache to demonstrate denied restricted writes and allowed trusted publication. Verify sensitive-read restrictions where required. Never poison the production cache to demonstrate the risk.',
'Define detection, disabling risky reuse, and trusted recomputation for suspect artifacts. Keep cache recovery separate from deletion of canonical source, worktrees, or persistent databases.'
], 'Only a directory label separates untrusted and release jobs: require real permissions instead of claiming namespace security.', 'A fork job can run tests but cannot upload results into the protected release cache; a fixture demonstrates denied writes with the restricted identity.', [('Nx cache deprecation','https://nx.dev/docs/reference/deprecated/self-hosted-cache-packages'),('Docker cache backends','https://docs.docker.com/build/cache/backends/')], ['cache','supply chain','credentials','docker','ci'])

skill('worktree-resource-isolation','Worktree Resource Isolation','Parallel engineering','Manage parallel lanes with separate source, mutable output, port, database, queue, process, lease, and recoverable cleanup ownership.',[
'Select an authorized worktree and record base, branch, owner, owned paths, and exclusions. Worktree separation does not isolate credentials, processes, database effects, or all filesystem access.',
'Use the existing allocator to reserve ports, build directories, compiler state, databases, queues, and reports atomically. Avoid check-then-use collisions. Share compatible immutable artifacts, not writable outputs.',
'Preflight actual CLI/MCP/language-server worktree bindings and resource ownership. Apply credentials and external-action restrictions separately from diff allowlists. Keep public records free of private paths and secrets.',
'Track activity and bounded leases through the existing lifecycle mechanism. Preserve interrupted changes and diagnostics. An expired lease is a reason to inspect, not proof that deletion is safe.',
'Release only positively owned inactive resources after checking unmerged source. Test collision, abandonment, and concurrent allocation in disposable fixtures. Avoid broad prune, clean, database-drop, or kill operations across lanes.'
], 'An expired lane lease still has an active process: preserve resources and reconcile ownership before cleanup.', 'Two Git worktrees share compiler state and a test database; preflight detects the collision and allocates private mutable resources while immutable downloads remain reusable.', [('Git worktrees','https://git-scm.com/docs/git-worktree'),('Docker cache optimization','https://docs.docker.com/build/cache/optimize/')], ['worktrees','isolation','resources','leases','parallel'])

skill('bounded-context-assembly','Bounded Context Assembly','Parallel engineering','Assemble task-sized context from current canonical source, accepted contracts, graphs, and semantic tools while tracking freshness and missing information.',[
'Identify the actual task question and accepted base. Read authoritative instructions and candidate state. Separate approved decisions from experiments, historical notes, and summaries.',
'Use existing graphs for owners/dependencies and language services for symbol/type questions. Retrieve the exact interfaces, tests, and nearby implementation required. Do not invent an indexer or vector database for a known-source question.',
'Attach paths, revisions or observed edits, and relevant tool identities. Detect a context service rooted in another checkout. State conflicts and apply canonical ownership rules instead of silently combining inconsistent sources.',
'Assemble goal, constraints, owned/excluded paths, contracts, selected evidence, and unresolved questions. Summaries supplement canonical files. Exclude secrets, customer records, and unrelated personal data.',
'Confirm delegated agents can access the references and tools in their own lanes. Parent connectivity does not establish child capability. Refresh the packet after relevant source or contract changes.'
], 'A packet predates an accepted API schema change: refresh affected context and mark earlier conclusions stale.', 'A retry-handling agent receives the accepted effect contract, activity code, failing case, and its own bindings, not an entire private company wiki.', [('Nx graph exploration','https://nx.dev/docs/features/explore-graph'),('gopls','https://go.dev/gopls/features/'),('Agent Skills','https://agentskills.io/specification')], ['context','graphs','agents','delegation','canonical sources'])

skill('toolchain-reproducibility','Toolchain Reproducibility','Infrastructure','Compare actual compiler, runtime, package-manager, container, and agent-tool identities across environments and verify targeted drift corrections.',[
'Read canonical version/dependency locks, then inspect executables used by the CLI, editor, app server, containers, and agents. Record versions, architecture, command resolution, and relevant configuration.',
'Separate tool installation locks from language dependency locks. A qualified installer such as mise does not replace pnpm-lock.yaml, go.sum, or container image identity.',
'Probe required flags, APIs, protocol behavior, and target-platform execution through actual entry points. Matching major versions are insufficient where integrations rely on specific capabilities.',
'Classify environment differences as required, compatible, or unresolved. Propose the smallest owned correction. Do not replace global machine configuration or install across inaccessible devices without authorization.',
'Repeat the original probes after changes, update relevant build/cache identity, and preserve rollback. Do not declare synchronization from one version file or remove locks to hide resolution problems.'
], 'Only one of two developer machines is accessible: the other remains uninspected, not synchronized.', 'The CLI uses a newer compiler while an app server and container remain older; verify each actual execution path after its approved correction.', [('mise.lock','https://mise.jdx.dev/dev-tools/mise-lock.html'),('Go toolchains','https://go.dev/doc/toolchain'),('Node packages','https://nodejs.org/api/packages.html')], ['toolchain','versions','mise','node','containers'])

skill('docker-development-loop','Docker Development Loop','Infrastructure','Distinguish file synchronization, restart, recompilation, image rebuild, and platform validation in a container loop that preserves owned application state.',[
'Map source, dependency, configuration, and image changes to necessary actions. Go source sync alone does not replace a running binary. Identify which paths require compile, restart, or image rebuild.',
'Review build context, ignores, COPY/layer boundaries, cache mounts, generated inputs, and secret handling. Avoid sending private/unrelated files or baking credentials into image layers.',
'Qualify installed Compose Watch behavior and test representative changes for each action. Verify the running endpoint or process actually reflects the edit; a sync log is not reload evidence.',
'Record build/runtime OS and architecture and compare native/emulated paths only with matched end-to-end workload and transfer costs. Give each active database server and lane its own writable state.',
'Test production images through real entry points, health/shutdown behavior, and affected integrations. A development bind mount is not a release artifact. Preserve persistent volumes during narrow development repairs.'
], 'Two PostgreSQL containers share one writable data directory: reject that resource allocation instead of treating it as reusable cache.', 'A Go handler edit recompiles and restarts the process; a dependency lock edit rebuilds the dependency image path. The owned test database persists.', [('Compose Watch','https://docs.docker.com/compose/how-tos/file-watch/'),('Docker caching','https://docs.docker.com/build/cache/optimize/'),('Multi-platform builds','https://docs.docker.com/build/building/multi-platform/')], ['docker','compose','buildkit','containers','dev loop'])

skill('integration-artifact-promotion','Integration Artifact Promotion','Infrastructure','Validate combined parallel changes and promote identified artifacts while preserving independent release approval, integration capacity, and recovery.',[
'Record the actual integration base, proposed branches, and preceding queued changes. Use a qualified queue or protected serialized integration. Independently green branches are not evidence that their combination works.',
'Reserve validation/integration resources separately from model agents, compiler threads, databases, tests, and image builds. Reduce admission when the integration queue saturates instead of endlessly increasing fan-out.',
'Bind checks to candidate source, contracts, toolchain, fixtures, and artifact digests. Detect edits after verification and distinguish fresh execution from cache restoration with a qualified producer.',
'Promote the validated object where supported rather than rebuild an unverified replacement. Record environment configuration separately and coordinate schema/API/worker transitions beyond what source graphs can infer.',
'Keep release authorization separate from build success. After an authorized deployment, verify the actual environment and a bounded behavior path. Preserve the prior artifact and compatible rollback/recovery.'
], 'Deployment rebuilds from a newer untested commit: require new evidence or use the previously validated artifact.', 'Two branches change a response and its consumer incompatibly. The combined candidate fails before promotion despite each branch passing independently.', [('GitHub merge queues','https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue'),('Build attestations','https://docs.docker.com/build/metadata/attestations/')], ['integration','artifacts','release','ci','merge queue'])

skill('mcp-adapter-design','MCP Adapter Design','MCP and bundles','Design thin MCP adapters with bounded schemas, trusted application identity, shared authorization, and explicit effects rather than treating instructions as permissions.',[
'Map guidance/context to suitable resources or prompts and executable operations to tools. A skill file is not an MCP server. Avoid remotely exposing every internal helper without a concrete operational contract.',
'Reuse shared application policy and use cases while keeping transport parsing/error translation thin. Do not allow arbitrary tenant, filesystem root, or elevated identity selection through client arguments.',
'Define schemas, bounds, pagination, timeout/cancellation, error categories, and effects. Avoid general arbitrary-shell tools. Tool annotations describe behavior; enforcement belongs in the server and application.',
'Validate credentials, audience, scopes, and required approval at execution. Do not pass through unrelated downstream tokens or treat untrusted tool output as authoritative instructions.',
'Test initialization/capabilities, discovery, malformed arguments, oversized output, cancellation, authorization, tenant boundaries, and effect errors. Verify delegated-agent access independently from the parent connection.'
], 'A client supplies another tenant’s ID in valid JSON: enforce trusted identity and reject unauthorized access regardless of schema validity.', 'A bounded check tool takes an approved check ID and validated lane ID; the server maps them to allowed commands rather than accepting a shell string.', [('MCP tools','https://modelcontextprotocol.io/specification/2025-11-25/server/tools'),('MCP security','https://modelcontextprotocol.io/docs/2025-11-25/tutorials/security/security_best_practices')], ['mcp','adapters','tools','authorization','resources'])

skill('provider-adapter-contracts','Provider Adapter Contracts','Integrations','Integrate providers through capability-aware contracts, normalized outcomes, bounded retries, authenticated callbacks, and explicit reconciliation/cancellation differences.',[
'Record input/output limits, asynchronous behavior, lookup, idempotency, cancellation, rate/cost policy, and callback verification per actual provider/version. Normalize common behavior without hiding unsupported features.',
'Define validated application request/result shapes, provider reference storage, error categories, and sensitive fields. Keep provider signing, polling, and wire translation inside thin adapters.',
'Distinguish rejected, accepted, running, completed, failed, cancelled, and indeterminate states as required. Apply actual retry/rate guidance and reconcile ambiguous submissions before repeating expensive effects.',
'Authenticate callbacks using the provider’s documented mechanism and raw-body requirements. Deduplicate events, tolerate ordering differences, and reconcile authoritative state. Transport acknowledgment need not mean downstream completion.',
'Test success, invalid inputs, rate limits, timeouts, duplicate/out-of-order callbacks, unsupported capabilities, and cancellation through public-safe fixtures. Reserve real integration for authorized sandbox credentials and avoid paid production smoke calls.'
], 'Submission timed out before receiving the provider reference: reconcile if supported or report indeterminate rather than blindly submit again.', 'Two image providers differ on post-acceptance cancellation; report the difference and reconcile a late success instead of promising both jobs stopped.', [('OpenAPI','https://spec.openapis.org/oas/v3.1.1.html'),('Webhook behavior example','https://docs.stripe.com/webhooks')], ['providers','adapters','webhooks','retries','capabilities'])

skill('tenant-authorization-boundaries','Tenant Authorization Boundaries','Security and state','Enforce tenant-scoped operations across transports, jobs, data, and caches using trusted identity and independent cross-tenant denial tests.',[
'Map sessions, service accounts, jobs, memberships, and resource ownership. Derive effective tenant/permissions from trusted context; a request tenant ID is not proof of membership.',
'Apply shared application authorization across HTTP, MCP, CLI, workers, storage, and administrative paths. Decide which jobs use an accepted authorization snapshot and which recheck policy, including revocation consequences.',
'Review query scopes, row security, cache keys, storage paths, search/vector retrieval, and signed URLs. Test the actual PostgreSQL executing role; owners and bypass roles can behave differently from intended application roles.',
'Use independent fixtures for two tenants and role variants. Attempt direct-object access, list/search leaks, mutations, stale credentials, and job/callback confusion. Assert absent side effects as well as response errors.',
'Keep audit correlation attributable without secrets or sensitive payloads. Test role changes and revocation at their defined boundary. Successful denial fixtures are scoped evidence, not a complete security certification.'
], 'Tests run as a table owner that bypasses the intended row policies: repeat with the actual application role and explain the difference.', 'A callback identifies a job; the worker loads tenant context from trusted stored ownership rather than an untrusted callback tenant field.', [('PostgreSQL row security','https://www.postgresql.org/docs/current/ddl-rowsecurity.html'),('MCP security','https://modelcontextprotocol.io/docs/2025-11-25/tutorials/security/security_best_practices')], ['tenancy','authorization','rbac','service accounts','security'])

skill('usage-metering-idempotency','Usage Metering Idempotency','Security and state','Account for usage through stable event identities, explicit precision and settlement policy, duplicate protection, adjustments, and replayable reconciliation.',[
'Separate estimates, reservations, provider cost, customer usage, and settled billing. Use approved definitions for billable events, precision, refunds, and timing; do not invent policy inside an adapter.',
'Assign effect identities stable across retries and callbacks. Reject incompatible reuse and enforce uniqueness in authoritative persistence rather than relying on in-memory deduplication.',
'Model reservation, settlement, release, adjustment, and reversal as required. Preserve auditable history and explicit rounding/precision. Do not assume every usage unit or currency uses two decimals.',
'Coordinate ambiguous provider outcomes, cancellation races, partial results, and retries with durable job state. A local request failure does not prove no provider work occurred or authorize an automatic refund.',
'Test duplicate/out-of-order events, reconciliation replay, corrected quantities, negative adjustments, and concurrent settlement. Check totals and uniqueness in a real isolated store when transactional semantics matter.'
], 'Cancellation returns locally while the provider completes: reconcile using the accepted metering policy, not an assumed refund rule.', 'Three copies of a success event settle one usage operation once; a later approved correction creates a separate linked adjustment.', [('PostgreSQL isolation','https://www.postgresql.org/docs/current/transaction-iso.html'),('Provider idempotency example','https://docs.stripe.com/api/idempotent_requests')], ['metering','usage','idempotency','ledger','billing'])

skill('async-job-state-machines','Async Job State Machines','Security and state','Model durable jobs with legal transition authority, stable operation/attempt identity, guarded effects, cancellation races, and recoverable indeterminate outcomes.',[
'Define needed states and who may authorize each transition. Keep transient UI loading state separate from durable job state. State which evidence can establish acceptance, success, failure, cancellation, or ambiguity.',
'Distinguish logical jobs from attempts, provider submissions, callbacks, and assets. Define deduplication and stale-event handling so an obsolete attempt cannot overwrite a newer accepted result.',
'Specify races between completion, cancellation, and timeout. A cancellation request is not completed cancellation. Apply the accepted reconciliation policy rather than whichever event arrives last.',
'Guard state transitions and protected effects with appropriate durable concurrency control. Persist required result/error and correlation references without secrets. Bound retries and expose a recovery path for indeterminate outcomes.',
'Test duplicate success, late failure, stale attempts, repeated cancellation, crash/restart, and concurrent changes using an independent transition table. Assert side effects as well as state; real provider checks remain separate.'
], 'Success arrives after a cancellation request: reconcile using explicit race policy and authoritative evidence instead of inventing an event-order rule.', 'The client times out while an external export succeeds; stored provider identity allows attaching the asset without creating a duplicate job or false cancellation.', [('Temporal workflows','https://docs.temporal.io/workflows'),('Webhook ordering example','https://docs.stripe.com/webhooks')], ['jobs','state machines','events','cancellation','reconciliation'])

skill('asset-lineage-provenance','Asset Lineage and Provenance','Media pipelines','Track immutable asset identities and derivation operations with versioned metadata, integrity checks, and explicit access, privacy, and retention boundaries.',[
'Separate byte/version identity from access URLs. Signed URLs expire and renew without changing the asset. Record media type, length, checksum algorithm, and storage version where available.',
'Connect inputs, transformations, outputs, and execution identities. Record observed model/provider version, approved parameters, and source revisions. Distinguish multi-input compositions, partial outputs, and failures.',
'Preserve metadata through crops, transcodes, captions, thumbnails, voice changes, and exports. New bytes produce derived identities. Validate cross-resource references against tenant/access policy.',
'Keep personal source images, voices, prompts, and consent records protected. Apply approved deletion/retention rules to derivatives and shared references. Provenance metadata does not confer usage rights or establish consent.',
'Test missing parents, forbidden cycles, repeated imports, digest mismatches, expired URLs, partial failure, and cross-tenant links. Reconstruct a synthetic transformation chain and verify referenced bytes where possible.'
], 'A provider does not expose the model revision: record unknown provenance instead of inventing reproducibility, seeds, rights, or consent.', 'A synthetic illustration becomes a thumbnail and captioned video; each has its own bytes and derivation record, while renewing a download URL creates no new asset.', [('W3C provenance','https://www.w3.org/TR/prov-overview/')], ['assets','lineage','media','provenance','storage'])

skill('skill-bundle-composition','Skill Bundle Composition','MCP and bundles','Select canonical public skills and bind private repository context separately without copying instructions, silently installing packages, or broadening tool authority.',[
'Select by actual task outcomes rather than loading every instruction into every agent. Separate foundational guidance from optional domain procedures. A bundle is a discovery selection, not mandatory invocation of all members.',
'Use stable skill IDs and a reviewed pinned checkout. Resolve SKILL.md and supporting files to content hashes and preserve companion tools where needed. The repository resolver is read-only and does not install or execute selected packages.',
'Bind concrete repository roots, accepted contracts, approved check IDs/argv, identities, limits, and organization policy in a private adapter. Keep credentials, private knowledge, and company-specific paths outside public packages.',
'Keep host/repository policy and execution authorization independent. MCP resources/prompts provide guidance; tools perform bounded actions. Bundle metadata is not a permission grant, shell input, or proof that a child agent loaded a skill.',
'Reject unknown/duplicate IDs and unsafe paths, verify selected bytes against the accepted lock, and expose dirty or unknown provenance. Test intended/non-trigger behavior in each host before claiming compatibility; review source updates before changing a private pin.'
], 'A selection references a missing helper or traversal path: fail resolution and preserve the prior known selection rather than substituting another package.', 'Two internal adapters select the same durable-workflow instructions and bind different approved queues/checks; they do not maintain separate edited copies of those skill bodies.', [('Agent Skills','https://agentskills.io/specification'),('MCP resources','https://modelcontextprotocol.io/specification/2025-11-25/server/resources'),('MCP tools','https://modelcontextprotocol.io/specification/2025-11-25/server/tools')], ['bundles','skills','mcp','composition','private adapters'])

assert len(DATA)==30
entries=json.loads((R/'catalog/entries.json').read_text())
assert len([e for e in entries if e['kind']=='skill'])==6
for e in entries:
    if e['kind']=='skill': e['packageVersion']='0.1.0'
for s in DATA:
    p=R/'skills'/s['id']
    if p.exists(): raise RuntimeError('Refuse to overwrite '+str(p))
    (p/'references').mkdir(parents=True)
    text='---\nname: '+s['id']+'\ndescription: '+json.dumps(s['description'])+'\nmetadata:\n  version: "0.1.0"\n  collection: "jordans-agent-toolkit"\n---\n# '+s['title']+'\n\nOriginal, project-agnostic instructions. Agent-host effectiveness remains experimental.\n\n## When to use\n\n'+s['description']+' Use for an actual task in this domain, under the consuming repository\'s approved policies.\n\n## When not to use\n\nDo not impose this procedure on unrelated or trivial work. Do not migrate tools, install services, perform production effects, publish, or delete resources without the task\'s required authorization.\n\n## Inputs and tailoring\n\nResolve the task goal, accepted source/contract baseline, relevant paths, installed versions, actual project-owned commands, effect policy, and required evidence. Read existing configuration before asking for information it already contains. Concrete repository roots, credentials references, command bindings, and private policies belong in the consuming adapter, not this public skill.\n\n## Procedure\n\n'
    text+='\n\n'.join('### '+str(i)+'. '+['Establish the boundary','Choose the supported contract','Implement or qualify the path','Exercise failure and integration seams','Verify and hand back evidence'][i-1]+'\n\n'+step for i,step in enumerate(s['steps'],1))
    text+='\n\n## Output\n\nReturn a task-sized implementation or review record containing the accepted invariant, source/environment identity, concrete decisions and changed paths, actual check results, evidence locations, remaining uncertainty, and next action. Distinguish passed, failed, blocked, and not-run checks; package shape is not behavior evidence.\n\n## Failure handling\n\n'+s['boundary']+' When access or prerequisites are unavailable, preserve existing work and report the smallest missing input. Do not fabricate commands, results, compatibility, or successful external effects.\n\n## Example\n\n'+s['example']+' This is a synthetic example, not a completed production or agent-host run.\n\n## Evaluation\n\nUse `references/scenarios.json` for intended, boundary, and non-trigger evaluation inputs. Keep their status not-run until a separate real host evaluation records actual outcomes.\n\n## Technical references\n\n'+'\n'.join('- ['+t+']('+u+')' for t,u in s['refs'])+'\n\nConsult documentation for the installed versions before using version-sensitive APIs. These are underlying-technology references, not copied upstream skill bodies.\n'
    (p/'SKILL.md').write_text(text)
    cases=[{'id':s['id']+'-trigger','kind':'trigger','input':'An authorized task requires: '+s['description'],'expected':'Resolve actual inputs and versions, follow the domain procedure, and return implementation/review evidence with explicit limitations.'},{'id':s['id']+'-boundary','kind':'boundary','input':s['boundary'],'expected':'Apply the stated boundary response, preserve unrelated work, and do not convert an unsupported or ambiguous condition into a pass.'},{'id':s['id']+'-non-trigger','kind':'non-trigger','input':'Correct a spelling mistake in an unrelated Markdown document.','expected':'Make only the authorized small correction; do not activate this domain workflow or change tooling, credentials, services, or data.'}]
    (p/'references/scenarios.json').write_text(json.dumps({'schemaVersion':1,'skill':s['id'],'status':'not-run','cases':cases},indent=2)+'\n')
    entries.insert(len(entries)-3,{'id':s['id'],'kind':'skill','origin':'original','stage':'experimental','category':s['category'],'sourcePath':'skills/'+s['id']+'/SKILL.md','packageVersion':'0.1.0','tags':s['tags'],'scenarioPath':'skills/'+s['id']+'/references/scenarios.json','requires':['Accepted task and source/contract baseline','Actual project toolchain and check commands','Authorized isolated evaluation environment'],'outcome':s['description'],'testedHosts':[],'evidence':[],'author':"Jordan's Agent Toolkit · AI-assisted",'note':'Original project-agnostic procedure with technical references and not-run synthetic evaluation inputs. Agent-host effectiveness is not established.'})
(R/'catalog/entries.json').write_text(json.dumps(entries,indent=2,ensure_ascii=False)+'\n')
