import json
from pathlib import Path
R=Path('.')
DATA=[]
def add(id,title,category,description,steps,output,scenario,boundary):
 DATA.append(dict(id=id,title=title,category=category,description=description,steps=steps,output=output,scenario=scenario,boundary=boundary))
add('goal-decomposition','Goal Decomposition','Agent orchestration','Turn a broad engineering goal into independently reviewable outcomes, explicit uncertainty, dependency edges, and a bounded first execution wave.',[
('Define the finish line','Read the accepted request, constraints, and relevant repository state. Describe what a user, caller, or operator must observe when the goal is met. Separate required outcomes from suggested implementation. Preserve unresolved behavior rather than asking a worker to invent it.'),
('Split at evidence boundaries','Create tasks around observable artifacts or behaviors. Put foundational contract decisions before dependent implementations. Avoid slicing only by file count, creating one agent per function, or parallelizing several agents onto an unresolved shared schema.'),
('Make each dependency explain itself','For each edge, state the required input and who accepts it. Record ownership, exclusions, independent check IDs, and a handoff. Use the existing Work Packet Planner to validate graph cycles and conflicting ownership instead of inventing a second task schema.'),
('Choose the first useful wave','Distinguish ready, decision-blocked, resource-blocked, and deferred work. Prefer a small validated end-to-end path before wide fan-out. A complete graph does not authorize execution, and a planned check is not a result.')],
 'A goal contract, task graph, edge rationale, acceptance owner, and first ready wave.',
 'An export feature needs a wire contract, two adapters, a client, and acceptance tests. The contract is accepted before adapter/client work fans out; integration validates their combination.',
 'Two proposed tasks both own the API specification with no ordering: assign one owner or establish a dependency before dispatch.')
add('agent-capability-discovery','Agent Capability Discovery','Agent orchestration','Build an expiring capability inventory from actual worker and tool probes while separating advertised, observed, unavailable, and authorized operations.',[
('Identify the execution environment','Record host, tool adapter, repository/worktree binding, supported model selection, and configured limits. Inspect current tools before assuming that a name, installed plugin, or parent connection implies child-agent availability.'),
('Probe narrowly','Use read-only capability discovery and a small approved smoke probe. Record operation, version, response, and time. Do not spend provider credits, install global configuration, or invoke write operations just to discover capabilities.'),
('Separate capability from authority','Record technical availability and permitted effects independently. A browser can navigate without being authorized to send a message. Keep credentials and private roots out of public registries; a capability tag cannot elevate authority.'),
('Bind and expire the inventory','Give each worker a stable identifier, capacity, supported phases, and an expiry. Recheck after configuration or permission changes and inside delegated workers. Agentflow validates a supplied registry; it does not perform these live probes.')],
 'A versioned registry plus probe evidence, expiry, missing capabilities, and distinct authorization notes.',
 'A parent has browser tools but its coding child does not. Route UI verification to a worker with a verified browser instead of assuming inherited access.',
 'A registry is expired or rooted in another worktree: refresh it or report the task blocked, not supported.')
add('agent-task-routing','Agent Task Routing','Agent orchestration','Match ready tasks to qualified workers using required capabilities, phase, effect policy, availability, and measured tradeoffs without hardcoding provider superiority.',[
('Describe requirements before executors','For each task, specify its needed capabilities, scope, accepted input identity, execution phase, and allowed effects. A language label alone does not establish database, browser, or private-repository access.'),
('Filter before ranking','Exclude unavailable, expired, unauthorized, incompatible, or capacity-exhausted workers. Then apply a deterministic configured preference among qualifying candidates. Agentflow rank is an explicit policy value, not an automatically learned quality score.'),
('Treat fallback as a new decision','Recheck context size, structured-output needs, policies, credentials, and budget before changing workers or models. Preserve the same acceptance contract. Do not route to a paid API or weaker permission boundary simply because a subscription worker is unavailable.'),
('Measure the decision','Record candidates, exclusion reasons, chosen worker, expected limits, and observed outcome. Compare completed accepted work and human intervention, not raw response speed. Leave unknown usage or pricing unknown.')],
 'A routing decision with qualification evidence, tie-breaking policy, fallback conditions, and explicit exclusions.',
 'A browser-only verification task excludes two fast coding workers; an eligible browser worker wins despite a higher configured rank.',
 'No candidate satisfies the required effect policy: return no eligible worker instead of widening permissions.')
add('parallel-dispatch-planning','Parallel Dispatch Planning','Agent orchestration','Select genuinely ready parallel work without colliding on shared files, mutable resources, unstable contracts, or review capacity.',[
('Verify readiness','Read the current graph and accepted dependencies. Submitted work is not accepted work; starting a child against an unreviewed upstream artifact can multiply rework. Keep decisions and scope blocks explicit.'),
('Inspect collision domains','Check file and directory ownership, generated outputs, compiler state, ports, databases, queues, and shared provider quotas. A worktree only separates some source state. Account for running or indeterminate previous attempts before scheduling replacements.'),
('Admit within a shared budget','Reserve tokens and resource slots for the proposed wave, plus capacity for verification/integration. Keep LLM worker count distinct from compiler and database parallelism. Use Agentflow schedule as an offline admission proposal, not an actual dispatcher.'),
('Revalidate at the execution boundary','The private launcher must atomically reserve resources, confirm approvals and context freshness, and start only the selected bounded operation. Repeatedly running a planning command does not reserve anything or make its proposals unique.')],
 'Selected tasks and workers, resource/token reservations, deferred tasks with reasons, and launch-time checks.',
 'Two independent adapters can run together, but the third implementation waits so review retains a slot. Their shared generated client has one upstream owner.',
 'An interrupted task may still be running on the same files: reconcile it before admitting a conflicting replacement.')
add('subagent-execution-contract','Subagent Execution Contract','Agent orchestration','Give a delegated worker a bounded goal, accepted source identity, explicit tools/effects, resource limits, check requirements, and a result envelope.',[
('Resolve the binding','Use real repository paths and accepted contract/source revisions in the private adapter. Include the task ID, attempt ID, context fingerprint, owned/read-only/excluded paths, and prerequisites. Do not include tokens or secrets in the message.'),
('State permissions independently','List the permitted tools and effect classes, approval requirements, and escalation route. Bind technical controls in the host/server. Instructions alone do not sandbox the worker, and the parent cannot delegate authority it does not possess.'),
('Define completion and interruption','Specify expected artifacts, independent acceptance checks, budget/deadline, progress signals, and stop conditions. Distinguish submitted output from reviewer acceptance. Explain how to preserve partial work and report indeterminate effects after interruption.'),
('Confirm the child sees the contract','Probe actual context and tool access in the child environment. Have it report unavailable bindings before work starts. Bind returned output to this attempt and input identity; reject results for a different task or stale base.')],
 'A task/attempt envelope plus an acceptance schema and a confirmed child capability binding.',
 'An adapter worker may edit one package and its tests but may not regenerate shared contracts; a discovered contract gap is returned to the owner.',
 'The child cannot access a required file or tool: return a precise blocked result rather than fabricate the missing context.')
add('subagent-lifecycle','Subagent Lifecycle','Agent orchestration','Track allocated, running, submitted, accepted, failed, and indeterminate work with explicit ownership and recoverable interruption.',[
('Separate observation from control','Use one authoritative run/task/attempt identity. Record transitions from actual launcher and reviewer observations, not optimistic agent messages. Agentflow records supplied events; it is not itself the launcher.'),
('Make transitions conditional','Require dependencies and stable inputs before starting. Require an output artifact and evidence before submission, and independent declared review before acceptance. Keep terminal outcomes distinct from a cancelled local wait.'),
('Handle interruptions conservatively','On lost contact, preserve work and treat effect state as unknown until the worker or provider is reconciled. Retain logical resource reservations while uncertain work may still be active. Do not assume lease expiry proves inactivity.'),
('Release owned resources deliberately','Let an ownership-aware private lifecycle controller release resources after inactivity and source-preservation checks. Retain diagnostic and acceptance records; never broadly clean worktrees or shared databases as a lifecycle shortcut.')],
 'A current state, transition history, owner/attempt identity, unresolved effects, and next safe action.',
 'A worker uploads an artifact, then disconnects before reporting success. The run remains indeterminate until the artifact and external effect are reconciled.',
 'A running attempt times out: keep it out of automatic retry until there is evidence that repeating it is safe.')
add('orchestration-resume','Orchestration Resume','Agent orchestration','Resume interrupted coordination from checked run records, reusing only current accepted artifacts and withholding ambiguous or stale work.',[
('Load authoritative state','Read the plan and journal from the accepted run. Validate schema, event ordering, input identity, and observed journal integrity. Hash chains detect inconsistency but do not authenticate the writer or prevent a malicious rewrite.'),
('Verify what can be reused','Match task input/contract/context digests and dependency identities. Check the bytes of accepted artifacts against their recorded hashes and propagate invalidation to descendants. A successful old message or unchanged task name is insufficient.'),
('Classify unfinished work','Keep queued tasks distinct from running, submitted, failed, and indeterminate tasks. Reconcile uncertain external effects before retry. Preserve charged or unknown usage; interruption does not restore a budget automatically.'),
('Propose only safe next work','Agentflow resume checks bounded local artifacts and returns a proposal. It does not launch or mutate prior runs. Changed plans or stale tasks require an explicit replan/review rather than an automatic rewrite of accepted history.')],
 'Reusable task IDs, stale or blocked results, unresolved attempts, consumed budget, and a bounded next-wave proposal.',
 'The contract artifact still matches its digest, but a derived review report was edited. Retain valid unrelated work and block dependent reuse until review is restored.',
 'An accepted artifact is missing or symlinked: mark it stale rather than follow an uncontrolled path or call the task complete.')
add('agent-failure-recovery','Agent Failure Recovery','Agent orchestration','Classify agent failures, preserve evidence, and choose bounded retries or reconciliation without repeating costly or unsafe effects.',[
('Classify the failure boundary','Separate task ambiguity, missing capability, dependency failure, tool/process failure, budget exhaustion, and lost contact. A provider timeout after acceptance differs from a request rejected before any effect.'),
('Preserve the attempt','Keep inputs, worktree changes, observed outputs, error and tool identities, and actual/unknown usage. Do not delete failed evidence or repair a report to make an attempt look successful.'),
('Choose a safe recovery','Retry only with a bounded attempt policy and a reason grounded in changed conditions. Reconcile indeterminate effects first. Route capability failures through discovery and policy again, not an automatic privileged or paid fallback.'),
('Escalate nonprogress','After the retry limit or repeated unchanged failure, stop new admission and provide a minimal reproducible handoff. Revisit the requirement or environment with its owner instead of repeatedly rewriting unrelated code.')],
 'Failure classification, preserved attempt evidence, retry/reconcile/escalate decision, remaining budget, and recovery check.',
 'A missing browser executable blocks verification. Repair the authorized test environment rather than rewriting the UI or marking browser checks passed.',
 'The prior attempt may have completed an irreversible effect: reconcile its state before authorizing any repeat.')
add('agent-result-integration','Agent Result Integration','Agent orchestration','Accept worker results against independent contracts and integrate combined changes without treating individual green branches as release evidence.',[
('Check result identity','Resolve the task, attempt, accepted base, owned diff, artifact identities, and checks actually executed. Reject results from a stale task contract or a different worktree. Treat an agent narrative as a summary, not the evidence source.'),
('Review independently','Use accepted requirements and checks that the implementation worker cannot silently weaken. Inspect prohibited side effects and out-of-scope changes. A different reviewer label is not proof of actual reviewer independence; bind that in the host.'),
('Validate the combination','Assemble the authorized integration candidate in an owned lane and run relevant combined checks. Reconcile contract, database, worker, and deployment-order interactions that isolated tests may miss.'),
('Record acceptance precisely','Distinguish submitted, accepted for integration, integrated, and published. Bind the record to the actual candidate and artifact. A journal acceptance event does not perform a Git merge or grant release permission.')],
 'Result acceptance or rejection, exact combined candidate, executed evidence, unresolved conflicts, and separate release status.',
 'A new server and client each pass their local fixtures but disagree on a nullable field. Combined integration rejects the mismatch before publication.',
 'The worker changed the acceptance test to match its output: restore independent review before accepting the result.')
add('orchestration-observability','Orchestration Observability','Agent orchestration','Capture task/attempt traces that explain delegation, queue time, context identity, resource pressure, and whether submitted work was actually integrated.',[
('Choose a minimal event contract','Correlate run, parent/child task, attempt, worker, source/context identity, phase, and declared effects. Use bounded metadata and artifact references instead of complete prompts or tool payloads.'),
('Record actual boundaries','Capture enqueue/start/finish/review/integration observations, failures, and visible usage. Separate queue time from model time and local verification from external latency. Unknown usage remains unknown; never synthesize token counts.'),
('Protect trace content','Redact credentials, private paths, user data, raw histories, and sensitive prompts before publication. Store raw traces under the product’s access/retention policy. Correlation IDs do not authorize access.'),
('Use traces to resolve decisions','Identify repeated tasks, stale context, blocked integration, lost children, and review bottlenecks. Replaying a journal reconstructs state; it does not replay nondeterministic model outputs or external effects.')],
 'A redacted trace index, phase timings where observed, result-to-integration mapping, and a focused bottleneck finding.',
 'Ten workers appear busy but completed work waits on one integration lane. Report integration queue growth instead of celebrating model throughput.',
 'Trace payloads contain a credential or private source prompt: restrict and redact them before sharing any diagnostic artifact.')
add('agent-permission-delegation','Agent Permission Delegation','Agent runtime','Reduce child-agent authority to the intersection of parent authority, task needs, organization policy, and currently approved effects.',[
('Enumerate authority sources','Separate authenticated identity, project membership, tool capability, policy, and task approval. Do not treat skill metadata, an agent role label, or a capability registry as a credential.'),
('Narrow the child binding','Grant only required tool operations, resources, tenants, effects, and lifetime. Reuse shared application authorization across transports. Avoid general shell or arbitrary filesystem access when a bounded operation is sufficient.'),
('Recheck changes','Define revocation, expiry, tenant changes, and delegation-chain limits at the real execution boundary. A child may have less authority than its parent; it must not gain authority by spawning grandchildren.'),
('Test denial paths','Use nonproduction fixtures to attempt unauthorized reads, writes, cross-tenant access, and privileged fallback. Assert absence of side effects, not only an error message. Agentflow checks declared metadata only; the private runtime enforces access.')],
 'A least-privilege delegation binding, policy/identity sources, expiry/revocation rules, and executed denial evidence.',
 'A parent can publish a repository, but its implementation child only receives local source and check access. Publication remains a separate approved operation.',
 'A child requests broader access than the parent holds: deny and escalate through the legitimate owner, never self-authorize.')
add('approval-gate-design','Approval Gate Design','Agent runtime','Place approvals at consequential effect boundaries and bind them to exact scope, inputs, identity, expiry, and execution policy.',[
('Identify the effect','Classify the requested operation and what can change outside the worker’s local lane. Treat read, local mutation, repository mutation, financial, and production effects separately; categories are a design aid, not a universal legal ranking.'),
('Bind approval to a specific decision','Present the actual target, diff or payload digest, expected consequences, limits, and alternatives. Record the approver identity and decision through a trusted application. Do not use a generic yes from an unrelated task.'),
('Validate just before execution','Recheck inputs, scope, policy, identity, expiry, and revocation. Changed consequential inputs require a new decision. Keep approved plans distinct from authorized execution and completed effects.'),
('Exercise invalid approvals','Test missing, expired, mismatched, revoked, and replayed decisions in a safe fixture. Agentflow’s approval records are caller-supplied scheduling metadata; they do not authenticate an approver or enforce server-side authorization.')],
 'Approval placement, immutable decision context, enforcement owner, expiration/revocation behavior, and boundary tests.',
 'A deploy was approved for artifact A. A later rebuild produces B; the launcher must not reuse A’s approval simply because the task ID is unchanged.',
 'A task input digest changes after approval: stop at the gate and obtain an appropriately scoped new decision.')
add('agent-budget-control','Agent Budget Control','Agent runtime','Reserve and reconcile agent, token, tool, and effect budgets without converting missing usage into free execution or silently switching billing paths.',[
('Define each unit and owner','Separate estimated token work, observed usage, provider cost, subscription limits, tool calls, elapsed time, and business effects. Establish the approved limits and reporting source; do not assume API credits and subscription allowances are interchangeable.'),
('Reserve before admission','Allocate conservative per-task and run-wide headroom before starting a wave. Include retries, reviewers, context assembly, and integration. A plan’s reservation is not an enforced provider quota; real limits belong in the launcher/gateway.'),
('Reconcile actual and unknown usage','Record the observed amount even when it exceeds a reservation. Preserve unknown usage conservatively until reconciled instead of dropping failed attempts. Pause further admission when the remaining budget cannot safely cover the next task.'),
('Make escalation explicit','Offer a smaller scope, a supported cheaper route, delayed work, or an approved budget change. Requalify model/capability and data policy for any fallback. Never silently spend on an API because a subscription worker ran out.')],
 'Budget definitions, reservations, actual/unknown usage, remaining capacity, and a policy-bound next-action decision.',
 'A failed worker used more tokens than expected. Its usage stays charged, so the next implementation waits while verification retains its budget.',
 'The provider exposes no usage count: mark it unknown and preserve a conservative charge, not zero.')
add('resource-aware-agent-scheduling','Resource-aware Agent Scheduling','Agent orchestration','Budget model workers separately from CPU, memory, database, browser, and build resources while reserving capacity for acceptance and integration.',[
('Inventory shared bottlenecks','Record active and uncertain model attempts, compiler/test subprocesses, databases, container builds, browser workers, and provider limits. Multiple agent pools can contend for the same machine even when their task graphs are independent.'),
('Define admission policy','Set global capacity and resource pools from measurements. Reserve a portion for verification/integration. Declare each task’s resource demand, then match ready work to both worker capacity and resource availability.'),
('Preserve uncertain reservations','When contact is lost, keep the potentially running attempt’s logical resources until the runtime confirms its state. A wall-clock timeout is not proof that a process or provider stopped.'),
('Measure accepted throughput','Increase concurrency in controlled steps and observe queue, rework, memory, and integrated completion. Agentflow provides a deterministic offline proposal; an atomic private allocator must enforce real reservations.')],
 'Resource pools, review reservation, admitted/deferred tasks with reasons, and measured bottleneck evidence.',
 'Two coding agents can share cached downloads but cannot each consume the only database fixture. Serialize or allocate distinct resources while keeping one review slot.',
 'Integration is saturated while implementation output grows: reduce new implementation admission rather than adding more workers.')
add('agent-loop-detection','Agent Loop Detection','Agent runtime','Detect repeated no-progress tool calls, equivalent patches, and unchanged failures using bounded evidence windows and explicit stop/escalation criteria.',[
('Define progress before counting activity','Use accepted artifacts, changed evidence, resolved uncertainty, or a new discriminating experiment as progress. Token output, tool volume, and repeated completion messages are not useful substitutes.'),
('Compare bounded attempts','Track task/input identity, tool request signature, failure signature, meaningful diff, and result. Redact sensitive arguments. Identify repeated equivalent work without storing full private prompts.'),
('Distinguish waits from thrash','Respect legitimate backoff, long-running work, and newly changed prerequisites. Set retry limits and an observation window appropriate to the operation, rather than a universal number of identical messages.'),
('Stop new churn','Preserve work and evidence, stop admitting equivalent attempts, and route to a bounded diagnosis or human decision. Do not kill unrelated processes, clear all caches, weaken tests, or spawn more agents to mask stalled work.')],
 'A loop signature, window and evidence, progress comparison, and safe pause/diagnosis/escalation decision.',
 'A worker alternates two import fixes while the same type error persists. Capture the cycle and inspect the actual package-resolution contract before another edit.',
 'A provider is still processing a legitimate long job: use bounded status polling instead of treating every unchanged status as failure.')
add('delegation-evaluation','Delegation Evaluation','Testing','Evaluate whether delegation improves accepted task outcomes using matched inputs, independent checks, repeated sessions, and explicit handoff/integration scoring.',[
('Specify the evaluation question','Compare a concrete delegated workflow with a no-delegation control or another qualified configuration. Pin task corpus, host/model/tool/skill revisions, budget, and acceptance rules before running.'),
('Control the conditions','Use fresh sessions and isolated public-safe fixtures. Keep requirements and acceptance tests independent from the worker’s implementation convenience. Document unavailable or incompatible comparison features instead of quietly disabling them.'),
('Score the full path','Measure correct completion, regressions, forbidden effects, interventions, duplicate work, context losses, integration success, elapsed time, and exposed usage. A child’s answer is not an accepted integrated change.'),
('Report the sample honestly','Repeat tasks, retain failures and sample counts, and show spread. Separate tool tests, scenario inputs, host runs, and real production outcomes. A passing schema or polished demo cannot establish superiority across all agents.')],
 'A matched evaluation protocol, complete run records, independent scores, limitations, and a scoped adoption decision.',
 'Two configurations both produce compiling patches; only one passes the independent cross-tenant denial and combined integration tests.',
 'A comparator cannot access the required browser: report the mismatch or redesign the comparison instead of claiming an easier run is a fair win.')
add('context-budget-planning','Context Budget Planning','Context and memory','Allocate task context by relevance and authority while preserving accepted constraints, high-value code, unresolved failures, and recoverable references.',[
('Inventory context needs','Identify the question, accepted contract, current source, active decisions, and evidence needed for the next action. Separate stable instructions from changing observations and untrusted retrieved content.'),
('Allocate the working packet','Prioritize constraints and relevant source before verbose history. Include concise summaries with source references and fingerprints, plus room for tool results. Do not guess exact token counts where the host does not expose them.'),
('Disclose progressively','Start with the smallest useful packet and retrieve deeper references only when needed. Keep omitted context discoverable through canonical paths. Do not remove constraints or failures merely to fit a context limit.'),
('Verify after reduction','Check that the child can still name its goal, accepted inputs, exclusions, required checks, and unresolved issues. Refresh source identities after changes. Provider prompt caching is a separate version-qualified optimization, not a reason to retain stale context.')],
 'A context allocation, included/omitted references, authority and freshness notes, and a child-readiness check.',
 'A worker fixing one retry seam receives the accepted effect contract, activity boundary, and failure case rather than an entire company knowledge base.',
 'The accepted schema is omitted to reduce size: restore that contract and remove lower-value history instead.')
add('context-checkpointing','Context Checkpointing','Context and memory','Preserve task state across compaction or handoff with source-backed decisions, unresolved failures, current artifacts, and explicit freshness checks.',[
('Capture the accepted state','Record the task/run/attempt IDs, accepted base, current source state, owned paths, active resources, artifacts, and completed checks. Distinguish pending decisions and proposed experiments from accepted requirements.'),
('Preserve uncertainty','Include failed experiments, blocked checks, ambiguous external effects, and remaining budget. Do not let a friendly summary erase the conditions that made an action unsafe or inconclusive.'),
('Link rather than duplicate','Use canonical decisions and source references with versions or observed fingerprints. Keep private context under private access policy and separate durable knowledge from a transient task checkpoint.'),
('Rehydrate cautiously','On resume, inspect referenced files and actual running/resource state. Recheck stale inputs and approvals. A checkpoint is context for recovery, not proof that commands ran, side effects completed, or a worker stopped.')],
 'A compact recovery packet with authoritative references, actual/unknown state, unresolved work, and required rechecks.',
 'Before compaction, the worker records that a provider call may have succeeded and the response is missing; the resumed worker reconciles instead of submitting it again.',
 'A checkpoint says tests passed but names no revision or output: retain the claim as unverified and rerun the required check where authorized.')
assert len(DATA)==18
entries=json.loads((R/'catalog/entries.json').read_text())
assert len(entries)==41 and len(list((R/'skills').glob('*/SKILL.md')))==36
for s in DATA:
 p=R/'skills'/s['id'];p.mkdir(parents=True,exist_ok=False);(p/'references').mkdir()
 body='---\nname: '+s['id']+'\ndescription: '+json.dumps(s['description'])+'\nmetadata:\n  version: "0.1.0"\n  collection: "jordans-agent-toolkit"\n---\n# '+s['title']+'\n\nOriginal, project-agnostic guidance. Agent-host effectiveness remains experimental.\n\n## When to use\n\n'+s['description']+' Activate only when the current task crosses this boundary.\n\n## When not to use\n\nDo not impose orchestration on a trivial edit or use these instructions to expand authority, start paid agents, alter production, or replace the consuming host\'s policies.\n\n## Procedure\n\n'
 body+='\n\n'.join('### '+h+'\n\n'+v for h,v in s['steps'])
 body+='\n\n## Output\n\n'+s['output']+' Tie observations to actual inputs and keep passed, failed, blocked, and not-run states distinct.\n\n## Failure handling\n\n'+s['boundary']+' Preserve partial work and report the smallest missing prerequisite rather than manufacture evidence.\n\n## Example\n\n'+s['scenario']+' This is a synthetic design scenario, not a completed host evaluation.\n\n## Companion tooling and evaluation\n\n[Agentflow commands and boundaries](https://github.com/jdavis-software/agent-toolkit/blob/main/docs/AGENTFLOW.md) document the optional offline coordination helper. It performs only its documented checks; the full procedure still needs a qualified host and private adapter. Use `references/scenarios.json` for trigger, boundary, and non-trigger evaluation inputs. Their `not-run` status is not a test result.\n'
 (p/'SKILL.md').write_text(body)
 cases={'schemaVersion':1,'skill':s['id'],'status':'not-run','cases':[{'id':s['id']+'-trigger','kind':'trigger','input':s['scenario'],'expected':s['output']},{'id':s['id']+'-boundary','kind':'boundary','input':s['boundary'].split(':')[0],'expected':s['boundary']},{'id':s['id']+'-non-trigger','kind':'non-trigger','input':'Fix one spelling mistake in an unrelated README without changing any behavior.','expected':'Apply the bounded edit; do not trigger an agent orchestration process or broaden execution authority.'}]}
 (p/'references/scenarios.json').write_text(json.dumps(cases,indent=2)+'\n')
 entries.append({'id':s['id'],'kind':'skill','origin':'original','stage':'experimental','category':s['category'],'sourcePath':'skills/'+s['id']+'/SKILL.md','packageVersion':'0.1.0','tags':['agents','orchestration',s['id'].replace('-',' ')],'scenarioPath':'skills/'+s['id']+'/references/scenarios.json','requires':['Accepted task and source identity','Qualified host and authorized private adapter'],'outcome':s['output'],'testedHosts':[],'evidence':[],'author':"Jordan's Agent Toolkit · AI-assisted",'note':'Original procedure. Synthetic evaluation inputs are not-run; host effectiveness is not established.'})
entries.append({'id':'agentflow','kind':'tool','origin':'original','stage':'experimental','category':'Agent orchestration','title':'Agentflow','description':'Offline task scheduling, capability matching, bounded budgets, run journals, and checked artifact reuse. No agent launching or model calls.','sourcePath':'tools/agentflow.mjs','docsPath':'docs/AGENTFLOW.md','requires':['Node >=22.12','Explicit JSON inputs and private execution bindings'],'outcome':'A deterministic coordination proposal or locally checked run record, without executing its tasks.','testedHosts':[],'evidence':[],'author':"Jordan's Agent Toolkit · AI-assisted",'note':'Coordination core, not a sandbox or live distributed scheduler. Registry, usage, approvals and reviews are caller-supplied.'})
categories=[
('agent-orchestration','Agent Orchestration','Plan bounded work, route capable workers, coordinate parallel lanes, and recover interrupted runs.','agents'),
('runtime-governance','Runtime & Governance','Define permissions, approval boundaries, budgets, and safe stop conditions for agent-assisted work.','shield'),
('context-memory','Context & Memory','Assemble relevant context, preserve decisions and failures, and resume with current source identities.','context'),
('typescript','TypeScript','Native TypeScript 7 adoption, domain types, ESM packages, and precise quality checks.','code'),
('go','Go Engineering','Cohesive services, bounded concurrency, deterministic tests, and evidence-led performance work.','terminal'),
('apis-integrations','APIs & Integrations','Evolve contracts, generate consumers, and connect providers without hiding important differences.','plug'),
('data-state','Data & State','Protect database invariants, evolve schemas, reconcile jobs, and account for usage consistently.','database'),
('durable-workflows','Durable Workflows','Build deterministic Temporal workflows, retry-safe activities, and compatible worker rollouts.','workflow'),
('testing-quality','Testing & Quality','Diagnose failures, design meaningful tests, review interfaces, and evaluate delegated work.','test'),
('devops-delivery','DevOps & Delivery','Keep toolchains reproducible, caches trustworthy, containers useful, and artifacts verified.','server'),
('media-pipelines','Media Pipelines','Track asset identities, derivation history, integrity, and appropriate data boundaries.','media'),
('mcp-tooling','MCP & CLI Tooling','Compose reusable skills, expose bounded MCP operations, and inspect executable developer tools.','tools')]
catdoc={'schemaVersion':1,'categories':[{'id':i,'title':t,'description':d,'icon':ic} for i,t,d,ic in categories]}
lookup={'Planning':'agent-orchestration','Parallel engineering':'agent-orchestration','Verification':'testing-quality','Debugging':'testing-quality','Testing':'testing-quality','Frontend':'testing-quality','TypeScript':'typescript','Go':'go','Contracts':'apis-integrations','Data':'data-state','Durable workflows':'durable-workflows','Infrastructure':'devops-delivery','MCP and bundles':'mcp-tooling','Integrations':'apis-integrations','Security and state':'data-state','Media pipelines':'media-pipelines','Developer tooling':'mcp-tooling','Agent orchestration':'agent-orchestration','Agent runtime':'runtime-governance','Context and memory':'context-memory'}
for e in entries:
 e['categoryId']=lookup[e['category']]
 if e['id']=='bounded-context-assembly':e['categoryId']='context-memory'
 if e['id']=='tenant-authorization-boundaries':e['categoryId']='runtime-governance'
 if e['kind']=='tool' and e['id']!='agentflow':e['categoryId']='mcp-tooling'
(R/'catalog/categories.json').write_text(json.dumps(catdoc,indent=2)+'\n')
(R/'catalog/entries.json').write_text(json.dumps(entries,indent=2,ensure_ascii=False)+'\n')
b=json.loads((R/'catalog/bundles.json').read_text())
assert len(b['bundles'])==8
b['bundles'] += [{'id':'agent-orchestration','title':'Agent Orchestration','description':'Bounded goals, capability-aware routing, coordinated dispatch, recoverable attempts, and reviewed integration.','version':'0.1.0','stage':'experimental','skills':[s['id'] for s in DATA if s['category']=='Agent orchestration']+['work-packet-planner','worktree-handoff','bounded-context-assembly']},{'id':'agent-runtime','title':'Agent Runtime and Governance','description':'Least-privilege delegation, exact approvals, budgets, context recovery, loop detection, and independent evaluation.','version':'0.1.0','stage':'experimental','skills':[s['id'] for s in DATA if s['category']!='Agent orchestration']+['tenant-authorization-boundaries','mcp-adapter-design','affected-verification']}]
(R/'catalog/bundles.json').write_text(json.dumps(b,indent=2)+'\n')
print(len(entries),'entries',len(b['bundles']),'bundles',len(categories),'categories')
