import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdtemp, rm, symlink, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { validateFlow, validateCapabilities, canonical, fingerprint, taskDigests, createRun, appendEvent, replayRun, schedule, artifactMatches } from '../tools/lib/agentflow.mjs';
const template=JSON.parse(await readFile(new URL('../examples/agentflow/plan.json',import.meta.url),'utf8'));
const workers=JSON.parse(await readFile(new URL('../examples/agentflow/capabilities.json',import.meta.url),'utf8'));
const plan=()=>structuredClone(template), registry=()=>structuredClone(workers), now=Date.parse('2026-01-01T00:00:00Z');
const propose=(p=plan(),r=registry(),opts={})=>schedule(p,r,{now,...opts});
const sha=b=>createHash('sha256').update(b).digest('hex');
const cli=new URL('../tools/agentflow.mjs',import.meta.url).pathname;
const call=(...args)=>spawnSync(process.execPath,[cli,...args],{encoding:'utf8'});
function event(run,taskId,type,extra={}){return {id:taskId+'-'+type+'-'+(run.events.length+1),taskId,taskDigest:taskDigests(run.plan).get(taskId),type,attempt:1,...extra};}
function record(run,e){return appendEvent(run,e,replayRun(run).head);}
function start(run,taskId='api'){return record(run,event(run,taskId,'started',{workerId:'fixture-editor'}));}
function outcome(run,taskId='api',type='failed',extra={}){return record(run,event(run,taskId,type,{usedTokens:0,evidence:['synthetic-output'],...extra}));}
async function temp(t){const d=await mkdtemp(join(tmpdir(),'agentflow-test-'));t.after(()=>rm(d,{recursive:true,force:true}));return d;}
async function accepted(t,ids=['api','ui']){
 const root=await temp(t);let run=createRun(plan());
 for(const id of ids){const bytes=Buffer.from('fixture-'+id);await writeFile(join(root,id+'.txt'),bytes);run=start(run,id);run=outcome(run,id,'submitted',{artifact:{path:id+'.txt',sha256:sha(bytes)}});run=record(run,event(run,id,'accepted',{reviewer:'fixture-reviewer',evidence:['synthetic-review']}));}
 return {root,run};
}
test('valid declared graph has two independent tasks then review',()=>assert.deepEqual(validateFlow(plan()).waves,[['api','ui'],['review']]));
test('canonical hashes ignore object key order but preserve array order',()=>{assert.equal(fingerprint({a:1,b:2}),fingerprint({b:2,a:1}));assert.notEqual(fingerprint([1,2]),fingerprint([2,1]));});
test('non-JSON and excessively nested values fail canonicalization',()=>{assert.throws(()=>canonical(undefined));assert.throws(()=>canonical(NaN));let d={};for(let i=0;i<41;i++)d={d};assert.throws(()=>canonical(d),/nesting/);});
test('cycles and unknown dependencies fail before scheduling',()=>{for(const dep of ['review','missing']){const p=plan();p.tasks[0].dependsOn=[dep];assert.throws(()=>validateFlow(p));}});
test('unordered shared ownership fails',()=>{const p=plan();p.tasks[1].owns=['api/'];assert.throws(()=>validateFlow(p),/ownership/);});
test('invalid policy, task limits and implicit approval fail',()=>{for(const patch of [{maxConcurrent:0},{reservedReviewSlots:3},{maxTokens:0},{allowedEffects:['root']}]){const p=plan();Object.assign(p.policy,patch);assert.throws(()=>validateFlow(p));}for(const patch of [{requiresApproval:undefined},{maxAttempts:11},{tokenBudget:-1},{inputDigest:'main'}]){const p=plan();Object.assign(p.tasks[0],patch);assert.throws(()=>validateFlow(p));}});
test('unexpected plan and task fields fail rather than become authority',()=>{assert.throws(()=>validateFlow({...plan(),shell:'anything'}));const p=plan();p.tasks[0].grant='admin';assert.throws(()=>validateFlow(p));});
test('changed upstream contract invalidates descendant identity only',()=>{const p=plan(),a=taskDigests(p);p.tasks[0].inputDigest='d'.repeat(64);const b=taskDigests(p);assert.notEqual(a.get('api'),b.get('api'));assert.notEqual(a.get('review'),b.get('review'));assert.equal(a.get('ui'),b.get('ui'));});
test('registry expiry and duplicate workers fail',()=>{const r=registry();r.validUntil='2025-01-01';assert.throws(()=>validateCapabilities(r,now),/expired/);const d=registry();d.workers.push(d.workers[0]);assert.throws(()=>validateCapabilities(d,now),/Duplicate/);});
test('scheduler proposes only ready tasks and executes nothing',async()=>{const r=await propose();assert.deepEqual(r.selected.map(x=>x.taskId),['api','ui']);assert.equal(r.execution,'none');assert.equal(r.tokensCommitted,200);assert.ok(r.blocked.some(x=>x.taskId==='review'&&x.reason==='dependencies-not-accepted'));});
test('capability matching is exact and unavailable workers are excluded',async()=>{const p=plan();p.tasks[0].capabilities=['edit-other'];const r=await propose(p);assert.ok(r.blocked.some(x=>x.taskId==='api'&&x.reason==='no-capable-worker'));const w=registry();w.workers[0].available=false;assert.equal((await propose(plan(),w)).selected.length,0);});
test('configured rank then stable worker identity choose among capable workers',async()=>{const r=registry();r.workers.push({...r.workers[0],id:'first-editor',rank:0});assert.ok((await propose(plan(),r)).selected.every(t=>t.workerId==='first-editor'));});
test('review slots limit new implementation fan-out',async()=>{const p=plan();p.policy.maxConcurrent=2;assert.equal((await propose(p)).selected.length,1);});
test('per-worker and resource pool capacity are independent constraints',async()=>{const w=registry();w.workers[0].capacity=1;assert.equal((await propose(plan(),w)).selected.length,1);const p=plan();p.policy.resources.cpu=1;const r=await propose(p);assert.equal(r.selected.length,1);assert.ok(r.blocked.some(x=>x.reason==='resource-capacity'));});
test('missing named resource and token oversubscription block admission',async()=>{const p=plan();p.policy.resources={};assert.equal((await propose(p)).selected.length,0);const q=plan();q.policy.maxTokens=100;const r=await propose(q);assert.equal(r.selected.length,1);assert.ok(r.blocked.some(x=>x.reason==='token-budget'));});
test('task effects cannot exceed declared policy',async()=>{const p=plan();p.tasks[0].effects=['production'];assert.ok((await propose(p)).blocked.some(x=>x.taskId==='api'&&x.reason==='effect-outside-policy'));});
test('approval metadata must match the current task digest and be unexpired',async()=>{const p=plan();p.tasks[0].requiresApproval=true;const r=registry();assert.ok((await propose(p,r)).blocked.some(x=>x.taskId==='api'&&x.reason==='approval-required'));r.approvals=[{taskId:'api',taskDigest:taskDigests(p).get('api'),expiresAt:'2099-01-01',reference:'synthetic-not-authenticated'}];assert.ok((await propose(p,r)).selected.some(x=>x.taskId==='api'));r.approvals[0].taskDigest='f'.repeat(64);assert.ok(!(await propose(p,r)).selected.some(x=>x.taskId==='api'));r.approvals[0].taskDigest=taskDigests(p).get('api');r.approvals[0].expiresAt='2025-01-01';assert.ok(!(await propose(p,r)).selected.some(x=>x.taskId==='api'));});
test('declared blockers prevent start and proposal',async()=>{const p=plan();p.tasks[0].blockedBy=['unaccepted contract'];assert.ok((await propose(p)).blocked.some(x=>x.reason==='declared-blocker'));assert.throws(()=>start(createRun(p)),/blockers/);});
test('starting a dependent task requires accepted prerequisites',()=>{const r=createRun(plan());assert.throws(()=>start(r,'review'),/Dependencies/);});
test('append preserves original record and rejects stale heads',()=>{const r=createRun(plan()),next=start(r);assert.equal(r.events.length,0);assert.equal(next.events.length,1);assert.throws(()=>appendEvent(next,event(next,'ui','started',{workerId:'fixture-editor'}),r.planDigest),/Stale/);});
test('hash-chain tampering and modified embedded plans fail replay',()=>{const r=start(createRun(plan()));r.events[0].event.workerId='forged';assert.throws(()=>replayRun(r),/hash/);const s=createRun(plan());s.plan.policy.maxTokens++;assert.throws(()=>replayRun(s),/digest/);});
test('duplicate event identities and mismatched task identities fail',()=>{let r=start(createRun(plan()));assert.throws(()=>record(r,event(r,'ui','started',{workerId:'fixture-editor',id:r.events[0].event.id})),/duplicate/);assert.throws(()=>record(r,event(r,'api','failed',{usedTokens:0,evidence:['x'],taskDigest:'0'.repeat(64)})),/identity/);});
test('completion needs explicit usage and evidence',()=>{const r=start(createRun(plan()));assert.throws(()=>record(r,event(r,'api','failed',{evidence:['x']})),/usage/);assert.throws(()=>outcome(r,'api','failed',{evidence:[]}),/evidence/);});
test('submission cannot be accepted by the same declared worker',()=>{let r=start(createRun(plan()));r=outcome(r,'api','submitted',{artifact:{path:'api.txt',sha256:'a'.repeat(64)}});assert.throws(()=>record(r,event(r,'api','accepted',{reviewer:'fixture-editor',evidence:['x']})),/Independent/);});
test('retry requires failure, reason and remaining attempts',()=>{let r=start(createRun(plan()));assert.throws(()=>record(r,event(r,'api','retry',{reason:'retry'})),/Retry/);r=outcome(r);assert.throws(()=>record(r,event(r,'api','retry')),/Retry/);r=record(r,event(r,'api','retry',{reason:'approved retry'}));r=record(r,event(r,'api','started',{attempt:2,workerId:'fixture-editor'}));r=record(r,event(r,'api','failed',{attempt:2,usedTokens:0,evidence:['x']}));assert.throws(()=>record(r,event(r,'api','retry',{attempt:2,reason:'again'})),/Retry/);});
test('indeterminate attempts reserve capacity and are never automatically retried',async()=>{let r=start(createRun(plan()));r=outcome(r,'api','indeterminate',{usedTokens:null});const s=await propose(plan(),registry(),{run:r});assert.ok(s.blocked.some(x=>x.taskId==='api'&&x.reason==='needs-reconciliation'));assert.equal(s.tokensCommitted,200);assert.throws(()=>record(r,event(r,'api','retry',{reason:'timeout'})),/Retry/);});
test('unknown usage charges reservation and observed overspend remains visible',async()=>{let r=start(createRun(plan()));r=outcome(r,'api','failed',{usedTokens:null});assert.equal(replayRun(r).states.get('api').chargedTokens,100);let s=start(createRun(plan()));s=outcome(s,'api','failed',{usedTokens:1200});const p=await propose(plan(),registry(),{run:s});assert.equal(p.overBudget,true);assert.equal(p.selected.length,0);});
test('reconciliation releases a running attempt only with explicit evidence',()=>{let r=start(createRun(plan()));assert.throws(()=>record(r,event(r,'api','reconciled-failure',{reason:'stopped'})),/evidence/);r=record(r,event(r,'api','reconciled-failure',{reason:'confirmed stopped',evidence:['synthetic-reconciliation']}));assert.equal(replayRun(r).states.get('api').status,'failed');assert.equal(replayRun(r).states.get('api').chargedTokens,100);});
test('valid accepted artifacts unlock review; hashes changing block reuse',async t=>{const {root,run}=await accepted(t);const r=await propose(plan(),registry(),{run,artifactRoot:root});assert.deepEqual(r.selected.map(x=>x.taskId),['review']);assert.deepEqual(r.reusable,['api','ui']);await writeFile(join(root,'api.txt'),'changed');const s=await propose(plan(),registry(),{run,artifactRoot:root});assert.ok(s.blocked.some(x=>x.reason==='stale-artifact'));assert.equal(s.selected.length,0);});
test('missing artifact root never silently trusts accepted results',async t=>{const {run}=await accepted(t);const r=await propose(plan(),registry(),{run});assert.equal(r.reusable.length,0);assert.ok(r.blocked.some(x=>x.reason==='needs-artifact-check'));});
test('changed input digest does not rerun accepted work or reuse descendants',async t=>{const {run,root}=await accepted(t);const p=plan();p.tasks[0].inputDigest='f'.repeat(64);const r=await propose(p,registry(),{run,artifactRoot:root});assert.ok(r.blocked.some(x=>x.taskId==='api'&&x.reason==='stale-inputs'));assert.equal(r.selected.length,0);assert.deepEqual(r.reusable,['ui']);});
test('missing, unsafe, symlink and oversized artifacts are rejected',async t=>{const root=await temp(t);const a={path:'file.txt',sha256:sha('x')};assert.equal(await artifactMatches(root,a),false);assert.equal(await artifactMatches(root,{...a,path:'../file.txt'}),false);await symlink('/etc/passwd',join(root,'file.txt'));assert.equal(await artifactMatches(root,a),false);await rm(join(root,'file.txt'));await writeFile(join(root,'file.txt'),Buffer.alloc(2*1024*1024+1));assert.equal(await artifactMatches(root,a),false);});
test('removed uncertain tasks retain reservations and require reconciliation',async()=>{const r=start(createRun(plan()));const p=plan();p.tasks=p.tasks.filter(t=>t.id!=='api');p.tasks.find(t=>t.id==='review').dependsOn=['ui'];const s=await propose(p,registry(),{run:r});assert.ok(s.blocked.some(x=>x.taskId==='api'&&x.reason==='removed-task-needs-reconciliation'));assert.equal(s.tokensCommitted,200);});
test('CLI discovery works and unsupported effects or commands do not execute',()=>{assert.equal(call('--help').status,0);for(const args of [['launch'],['plan'],['status','none','--out','x']])assert.notEqual(call(...args).status,0);});
test('CLI init creates restrictive output once and refuses overwrite',async t=>{const root=await temp(t);const p=join(root,'plan.json'),out=join(root,'run.json');await writeFile(p,JSON.stringify(plan()));assert.equal(call('init',p,'--out',out).status,0);assert.equal((await stat(out)).mode&0o777,0o600);const before=await readFile(out,'utf8');assert.notEqual(call('init',p,'--out',out).status,0);assert.equal(await readFile(out,'utf8'),before);assert.equal(call('verify',out).status,0);});
test('CLI rejects malformed JSON and input file symlinks',async t=>{const root=await temp(t),p=join(root,'bad.json');await writeFile(p,'not json');assert.notEqual(call('plan',p).status,0);await symlink(p,join(root,'link'));assert.notEqual(call('plan',join(root,'link')).status,0);});
