import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, symlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { hash, readText, canonical } from '../tools/lib/harness/common.mjs';
import { auditProfile, observeWorkspace } from '../tools/lib/harness/profile.mjs';
import { reconcileReadiness } from '../tools/lib/harness/readiness.mjs';
import { reconcileEvents, importCodexExec } from '../tools/lib/harness/events.mjs';
import { controllerCases,runControllerSuite } from '../tools/lib/harness/conformance.mjs';
import { fixtureController } from '../examples/harnesskit/controller-fixture.mjs';
const now=Date.parse('2026-09-18T00:00:00.000Z'), when=new Date(now).toISOString();
const sha='a'.repeat(64), git='b'.repeat(40);
const live={schemaVersion:1,observedAt:when,workspace:{rootSha256:sha,head:git,stateSha256:sha,dirty:false},fields:{nodeVersion:{observed:process.version,provenance:'host-probe',mutability:'startup'}}};
const profile={schemaVersion:1,gitRevision:git,requireClean:true,maxAgeSeconds:300,fields:{nodeVersion:process.version,authMode:'chatgpt'}};
const observation=()=>({...structuredClone(live),fields:{...live.fields,authMode:{requested:'chatgpt',resolved:'chatgpt',observed:'chatgpt',provenance:'runtime-response',mutability:'startup'}}});
test('profile reports requested/resolved/observed matches without field values',()=>{const r=auditProfile(profile,observation(),live,now);assert.equal(r.ok,true);assert.equal(JSON.stringify(r).includes('chatgpt'),false);});
test('profile configuration-only auth is unknown, not proof',()=>{const o=observation();o.fields.authMode.provenance='configuration';assert.equal(auditProfile(profile,o,live,now).checks.at(-1).status,'unknown');});
test('profile missing runtime field stays unknown',()=>{const o=observation();delete o.fields.authMode;assert.equal(auditProfile(profile,o,live,now).checks.at(-1).status,'unknown');});
test('profile catches an unexpected separately billed auth mode',()=>{const o=observation();o.fields.authMode.observed='api-key';assert.equal(auditProfile(profile,o,live,now).ok,false);});
test('profile does not echo caller-supplied secret-like strings',()=>{const o=observation();o.fields.authMode.observed='sensitive-value';assert.equal(JSON.stringify(auditProfile(profile,o,live,now)).includes('sensitive-value'),false);});
test('profile catches wrong worktree binding',()=>{const o=observation();o.workspace.rootSha256='c'.repeat(64);assert.equal(auditProfile(profile,o,live,now).ok,false);});
test('profile catches source edits after observations',()=>{const o=observation();o.workspace.stateSha256='d'.repeat(64);assert.equal(auditProfile(profile,o,live,now).checks.at(-1).status,'unbound');});
test('profile catches stale observations',()=>assert.equal(auditProfile(profile,observation(),live,now+301000).checks.at(-1).status,'stale'));
test('profile rejects future observations as not fresh',()=>assert.equal(auditProfile(profile,observation(),live,now-6000).ok,false));
test('profile catches dirty state when required',()=>assert.equal(auditProfile(profile,observation(),{...live,workspace:{...live.workspace,dirty:true}},now).ok,false));
test('profile rejects unsupported fields rather than silently ignoring them',()=>assert.throws(()=>auditProfile({...profile,fields:{adminPassword:'no'}},observation(),live,now),/field/));
const task={schemaVersion:1,id:'example/planning#12',codeRepository:'example/implementation',contractRevision:sha,baseRevision:git,maxAgeSeconds:300,dependencies:[{id:'example/planning#11',contractRevision:sha}]};
const snapshot=()=>({schemaVersion:1,observedAt:when,task:{id:task.id,codeRepository:task.codeRepository,contractRevision:sha,baseRevision:git,ready:true,ownership:'available'},dependencies:[{id:'example/planning#11',contractRevision:sha,state:'accepted',candidateRevision:git,acceptanceEvidenceSha256:sha}]});
test('readiness requires matching accepted prerequisites',()=>assert.equal(reconcileReadiness(task,snapshot(),now).ok,true));
test('filtered-out prerequisite blocks dispatch',()=>{const s=snapshot();s.dependencies=[];const r=reconcileReadiness(task,s,now);assert.equal(r.ok,false);assert.equal(r.checks.at(-1).reason,'unknown-prerequisite');});
test('closed prerequisite is not accepted',()=>{const s=snapshot();s.dependencies[0].state='closed';assert.equal(reconcileReadiness(task,s,now).ok,false);});
test('same issue number in another repository cannot satisfy dependency',()=>{const s=snapshot();s.dependencies[0].id='example/other#11';assert.equal(reconcileReadiness(task,s,now).ok,false);});
test('readiness distinguishes task and code repository',()=>{const s=snapshot();s.task.codeRepository='example/planning';assert.equal(reconcileReadiness(task,s,now).ok,false);});
test('stale accepted prerequisite is blocked',()=>{const s=snapshot();s.dependencies[0].contractRevision='d'.repeat(64);assert.equal(reconcileReadiness(task,s,now).ok,false);});
test('ready label does not replace available ownership',()=>{const s=snapshot();s.task.ownership='occupied';assert.equal(reconcileReadiness(task,s,now).ok,false);});
test('readiness rejects duplicate observations',()=>{const s=snapshot();s.dependencies.push(s.dependencies[0]);assert.throws(()=>reconcileReadiness(task,s,now),/dependency/);});
test('readiness rejects stale snapshot',()=>assert.equal(reconcileReadiness(task,snapshot(),now+301000).ok,false));
test('missing accepted evidence is not accepted',()=>{const s=snapshot();delete s.dependencies[0].acceptanceEvidenceSha256;assert.equal(reconcileReadiness(task,s,now).ok,false);});
const event=(n,input,output=0,basis='cumulative',epoch='1')=>({schemaVersion:1,eventId:`e${n}`,attemptId:'attempt-1',type:'usage',counterId:'tokens',counterEpoch:epoch,basis,usage:{inputTokens:input,outputTokens:output,cachedInputTokens:0,reasoningOutputTokens:0}});
test('cumulative 1200 then 1700 totals 1700, not 2900',()=>assert.equal(reconcileEvents([event(1,1200),event(2,1700)]).usage.totalTokens,1700));
test('stable identical event IDs are deduplicated',()=>{const e=event(1,1200);const r=reconcileEvents([e,e]);assert.equal(r.duplicates,1);assert.equal(r.usage.totalTokens,1200);});
test('changed content under the same event ID is rejected',()=>assert.throws(()=>reconcileEvents([event(1,1),event(1,2)]),/conflicting/));
test('equal delta observations with different IDs both count',()=>assert.equal(reconcileEvents([event(1,50,10,'delta'),event(2,50,10,'delta')]).usage.totalTokens,120));
test('counter resets require an explicit new epoch',()=>{const r=reconcileEvents([event(1,1200),event(2,10),event(3,20)]);assert.equal(r.ok,false);assert.equal(r.usage.inputTokens,1200);assert.equal(r.usage.coverage,'partial');});
test('new counter epoch starts a separate cumulative series',()=>assert.equal(reconcileEvents([event(1,1200),event(2,10,0,'cumulative','2')]).usage.inputTokens,1210));
test('one counter cannot mix delta and cumulative bases',()=>assert.throws(()=>reconcileEvents([event(1,1),event(2,2,0,'delta')]),/mixed/));
test('cached input is a subset, not additional tokens',()=>{const e=event(1,100,20);e.usage.cachedInputTokens=80;assert.equal(reconcileEvents([e]).usage.totalTokens,120);});
test('invalid breakdown cannot exceed its parent total',()=>{const e=event(1,10);e.usage.cachedInputTokens=11;assert.throws(()=>reconcileEvents([e]),/breakdown/);});
test('negative or unsafe counters are rejected',()=>{assert.throws(()=>reconcileEvents([event(1,-1)]),/usage/);assert.throws(()=>reconcileEvents([event(1,Number.MAX_SAFE_INTEGER),event(2,2,0,'cumulative','2')]),/overflow/);});
test('missing usage remains null',()=>{const r=reconcileEvents([{schemaVersion:1,eventId:'gap-1',attemptId:'a',type:'gap'}]);assert.equal(r.usage.totalTokens,null);assert.equal(r.ok,false);});
const binding={schemaVersion:1,attemptId:'attempt-1',runtimeVersion:'fixture-exec-v1'};
const stream=(u={input_tokens:100,cached_input_tokens:50,output_tokens:20})=>[{type:'thread.started',thread_id:'t1'},{type:'turn.started'},{type:'item.completed',item:{type:'agent_message',text:'private prompt or command output'}},{type:'turn.completed',usage:u}];
const jsonl=a=>a.map(e=>JSON.stringify(e)).join('\n');
test('exec import preserves totals, hides raw content and never accepts integration',()=>{const r=importCodexExec(jsonl(stream()),binding);assert.equal(r.usage.totalTokens,120);assert.equal(r.acceptance,'not-evaluated');assert.equal(JSON.stringify(r).includes('private prompt'),false);assert.equal(r.source.turnIdentity,'local-sequence');});
test('whole capture replay is deterministic',()=>assert.deepEqual(importCodexExec(jsonl(stream()),binding),importCodexExec(jsonl(stream()),binding)));
test('identical usage in two actual turns is not deduplicated',()=>{const s=stream();s.push(...stream().slice(1));assert.equal(importCodexExec(jsonl(s),binding).usage.totalTokens,240);});
test('duplicate terminal does not silently double-count',()=>{const s=stream();s.push(s.at(-1));const r=importCodexExec(jsonl(s),binding);assert.equal(r.ok,false);assert.equal(r.usage.totalTokens,120);});
test('dropped stream retains unknown usage and an unterminated turn',()=>{const r=importCodexExec(jsonl(stream().slice(0,3)),binding);assert.equal(r.ok,false);assert.equal(r.usage.totalTokens,null);});
test('failed turn is not accepted or successful',()=>{const s=stream();s.at(-1).type='turn.failed';assert.equal(importCodexExec(jsonl(s),binding).ok,false);});
test('unsupported source event creates a coverage gap',()=>assert.equal(importCodexExec(jsonl([...stream(),{type:'new.version.event'}]),binding).ok,false));
test('mixed source threads are rejected',()=>assert.throws(()=>importCodexExec(jsonl([...stream(),{type:'thread.started',thread_id:'t2'}]),binding),/mixed/));
test('malformed JSONL is rejected without its content',()=>assert.throws(()=>importCodexExec('secret malformed',binding),/invalid-jsonl/));
const identity={id:'fixture-controller',revision:'fixture-v1',kind:'fixture'};
test('all baseline synthetic controller cases pass',async()=>{const r=await runControllerSuite(()=>fixtureController(),identity);assert.equal(r.ok,true);assert.equal(r.results.length,7);});
for(const c of controllerCases)test(`controller oracle detects ${c.id}`,async()=>{const r=await runControllerSuite(()=>fixtureController(c.id),identity);assert.equal(r.ok,false);assert.equal(r.results.find(v=>v.caseId===c.id).passed,false);});
test('adapter exception cannot pass the suite',async()=>assert.equal((await runControllerSuite(async()=>{throw new Error('private error');},identity)).ok,false));
function gitFixture(){const p=mkdtempSync(join(tmpdir(),'harness-git-'));const run=args=>{const r=spawnSync('git',args,{cwd:p,encoding:'utf8',env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});assert.equal(r.status,0,r.stderr);};run(['init']);writeFileSync(join(p,'source.txt'),'initial');run(['add','.']);run(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture']);return p;}
test('actual Git observation detects untracked edits without exposing paths',()=>{const p=gitFixture();try{const before=observeWorkspace(p,now);writeFileSync(join(p,'new.txt'),'untracked');const after=observeWorkspace(p,now);assert.notEqual(before.workspace.stateSha256,after.workspace.stateSha256);assert.equal(after.workspace.dirty,true);assert.equal(JSON.stringify(after).includes(p),false);}finally{rmSync(p,{recursive:true,force:true});}});
test('CLI observe is a real bounded Git probe and invalid commands hide data',()=>{const p=gitFixture();try{const cli=fileURLToPath(new URL('../tools/harnesskit.mjs',import.meta.url));const r=spawnSync(process.execPath,[cli,'observe','--root',p],{encoding:'utf8'});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).workspace.dirty,false);const bad=spawnSync(process.execPath,[cli,'secret-value'],{encoding:'utf8'});assert.equal(bad.status,2);assert.equal(bad.stderr.includes('secret-value'),false);}finally{rmSync(p,{recursive:true,force:true});}});
test('bounded reader rejects symlink and oversized inputs',()=>{const p=mkdtempSync(join(tmpdir(),'harness-file-'));try{writeFileSync(join(p,'file'),'hi');symlinkSync(join(p,'file'),join(p,'link'));assert.throws(()=>readText(join(p,'link')),/symlink/);writeFileSync(join(p,'large'),Buffer.alloc(2*1024*1024+1));assert.throws(()=>readText(join(p,'large')),/file/);}finally{rmSync(p,{recursive:true,force:true});}});
test('canonicalization is key-order stable and depth-bounded',()=>{assert.equal(canonical({b:1,a:2}),canonical({a:2,b:1}));let d={};for(let i=0;i<60;i++)d={d};assert.throws(()=>canonical(d),/deep/);});

test('thread-only capture is an incomplete report, not a crash or a zero-usage pass',()=>{const r=importCodexExec(jsonl([{type:'thread.started',thread_id:'t1'}]),binding);assert.equal(r.ok,false);assert.equal(r.usage.totalTokens,null);});
test('source command outcome is retained without its command',()=>{const s=stream();s[2].item={type:'command_execution',status:'failed',exit_code:1,command:'sensitive command'};const r=importCodexExec(jsonl(s),binding);const e=r.events.find(e=>e.type==='item');assert.equal(e.exitCode,1);assert.equal(e.itemStatus,'failed');assert.equal(JSON.stringify(r).includes('sensitive command'),false);});
test('source reasoning usage is a subset of output',()=>{const r=importCodexExec(jsonl(stream({input_tokens:100,cached_input_tokens:50,output_tokens:20,reasoning_output_tokens:8})),binding);assert.equal(r.usage.totalTokens,120);assert.equal(r.usage.reasoningOutputTokens,8);});
test('exec capture without usage does not invent coverage',()=>{const s=stream();delete s.at(-1).usage;const r=importCodexExec(jsonl(s),binding);assert.equal(r.ok,false);assert.equal(r.usage.coverage,'partial');});
