import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,mkdirSync,rmSync,renameSync,symlinkSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {validatePlan,validateDebug,validateTestDesign,validateInterface,validScope} from '../tools/lib/contracts.mjs';
import {inspectWorktree,parseStatus} from '../tools/lib/worktree.mjs';
import {runCheck,verifyReceipt} from '../tools/lib/runner.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const sample=name=>JSON.parse(readFileSync(join(root,'examples/skillcheck',name+'.json'),'utf8'));
const clone=x=>structuredClone(x);
function git(dir,...args) {
 const r=spawnSync('git',['-c','user.name=Toolkit Test','-c','user.email=toolkit@example.invalid','-c','commit.gpgSign=false',...args],{cwd:dir,encoding:'utf8',env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});
 assert.equal(r.status,0,r.stderr); return r.stdout.trim();
}
function fixture(t) {
 const dir=mkdtempSync(join(tmpdir(),'jordan-skillcheck-'));
 t.after(()=>rmSync(dir,{recursive:true,force:true}));
 git(dir,'init','-q'); writeFileSync(join(dir,'value.txt'),'original\n');
 writeFileSync(join(dir,'.gitignore'),'ignored/\n');
 git(dir,'add','.');git(dir,'commit','-qm','synthetic fixture');return dir;
}
const run=(repo,code,opts={})=>runCheck({repo,id:'fixture',argv:[process.execPath,'-e',code],...opts});
test('independent tasks form a parallel wave before integration',()=>{const r=validatePlan(sample('plan'));assert.equal(r.ok,true);assert.deepEqual(r.waves,[['filters','search'],['integrate']]);assert.equal(r.checksExecuted,false);});
test('dependency cycles are rejected',()=>{const p=sample('plan');p.tasks[0].dependsOn=['integrate'];assert.equal(validatePlan(p).ok,false);});
test('unknown dependencies are rejected',()=>{const p=sample('plan');p.tasks[0].dependsOn=['missing'];assert.equal(validatePlan(p).ok,false);});
test('unordered shared files are rejected',()=>{const p=sample('plan');p.tasks[1].owns=['src/search/file.ts'];assert.match(JSON.stringify(validatePlan(p).errors),/overlap/);});
test('transitively ordered shared files are allowed',()=>{const p=sample('plan');p.tasks[1].owns=['src/search/file.ts'];p.tasks[1].dependsOn=['search'];assert.equal(validatePlan(p).ok,true);});
test('sibling prefixes are not false conflicts',()=>{const p=sample('plan');p.tasks[0].owns=['src/app/'];p.tasks[1].owns=['src/apple/'];assert.equal(validatePlan(p).ok,true);});
test('file versus directory at the same path conflicts',()=>{const p=sample('plan');p.tasks[0].owns=['src/app'];p.tasks[1].owns=['src/app/'];assert.equal(validatePlan(p).ok,false);});
test('a declared blocker propagates to dependent tasks',()=>{const p=sample('plan');p.tasks[0].blockedBy=['Contract not settled'];const r=validatePlan(p);assert.equal(r.ok,true);assert.deepEqual(r.waves,[['filters']]);assert.deepEqual(r.blocked,['search','integrate']);});
test('unmapped acceptance criteria are rejected',()=>{const p=sample('plan');p.tasks[0].acceptance[0].checkIds=['missing'];assert.equal(validatePlan(p).ok,false);});
test('duplicate tasks are rejected',()=>{const p=sample('plan');p.tasks.push(clone(p.tasks[0]));assert.equal(validatePlan(p).ok,false);});
test('shell strings are not command arrays',()=>{const p=sample('plan');p.tasks[0].checks[0].argv='node --test';assert.equal(validatePlan(p).ok,false);});
test('scope traversal, globs, metadata and absolute paths are rejected',()=>{for(const p of ['../x','/tmp/x','src/../x','src/**','.git/config','a/.Git/','C:/x','src//x','a\\b'])assert.equal(validScope(p),false,p);});
test('invalid plan shapes return failures',()=>{for(const p of [null,{},[],{schemaVersion:1,tasks:[null]}])assert.equal(validatePlan(p).ok,false);});
test('Git snapshot identifies a clean committed state without changes',t=>{const d=fixture(t),r=inspectWorktree(d);assert.equal(r.dirty,false);assert.equal(r.head,git(d,'rev-parse','HEAD'));assert.deepEqual(r.changes,[]);});
test('Git snapshot separates staged, unstaged and untracked paths',t=>{const d=fixture(t);writeFileSync(join(d,'value.txt'),'staged');git(d,'add','value.txt');writeFileSync(join(d,'value.txt'),'unstaged');writeFileSync(join(d,'other file.txt'),'untracked');const r=inspectWorktree(d);assert.deepEqual(r.changes.find(x=>x.path==='value.txt').layers,['staged','unstaged']);assert.deepEqual(r.changes.find(x=>x.path==='other file.txt').layers,['untracked']);});
test('untracked content changes invalidate the fingerprint',t=>{const d=fixture(t);writeFileSync(join(d,'new.txt'),'one');const a=inspectWorktree(d);writeFileSync(join(d,'new.txt'),'two');assert.notEqual(a.stateSha256,inspectWorktree(d).stateSha256);});
test('committed changes are compared with the explicit base',t=>{const d=fixture(t),base=git(d,'rev-parse','HEAD');writeFileSync(join(d,'value.txt'),'new');git(d,'add','.');git(d,'commit','-qm','change');const r=inspectWorktree(d,{base});assert.deepEqual(r.changes,[{path:'value.txt',layers:['committed']}]);});
test('scope violations fail without deleting work',t=>{const d=fixture(t);writeFileSync(join(d,'outside.txt'),'keep');const r=inspectWorktree(d,{scopes:['src/']});assert.equal(r.ok,false);assert.deepEqual(r.outOfScope,['outside.txt']);assert.equal(readFileSync(join(d,'outside.txt'),'utf8'),'keep');});
test('require-clean rejects uncommitted work',t=>{const d=fixture(t);writeFileSync(join(d,'value.txt'),'changed');assert.equal(inspectWorktree(d,{requireClean:true}).ok,false);});
test('rename captures both paths for scope ownership',t=>{const d=fixture(t);git(d,'mv','value.txt','renamed file.txt');const r=inspectWorktree(d);assert.deepEqual(r.changes.map(e=>e.path).sort(),['renamed file.txt','value.txt']);});
test('porcelain parser preserves embedded newline filenames',()=>{const r=parseStatus(Buffer.from('?? line\nbreak.txt\0R  new name\0old name\0'));assert.deepEqual(r[0].paths,['line\nbreak.txt']);assert.deepEqual(r[1].paths,['new name','old name']);});
test('untracked symlinks are hashed without reading their destinations',{skip:process.platform==='win32'},t=>{const d=fixture(t);symlinkSync('/definitely/not/a/real/target',join(d,'link'));assert.equal(inspectWorktree(d).dirty,true);});
test('missing or option-like baseline does not silently select main',t=>{const d=fixture(t);assert.throws(()=>inspectWorktree(d,{base:'nonexistent-ref'}));assert.throws(()=>inspectWorktree(d,{base:'--all'}));});
test('ignored state is explicitly outside the fingerprint coverage',t=>{const d=fixture(t),a=inspectWorktree(d);mkdirSync(join(d,'ignored'));writeFileSync(join(d,'ignored','cache'),'data');const b=inspectWorktree(d);assert.equal(a.stateSha256,b.stateSha256);assert.match(b.coverage,/excludes ignored/);});
test('runner records an actual successful process result',async t=>{const d=fixture(t),r=await run(d,'console.log("observed")');assert.equal(r.status,'passed');assert.equal(r.exitCode,0);assert.equal(r.stdout.text,'observed\n');assert.equal(verifyReceipt(r,d).ok,true);});
test('printing PASS cannot turn nonzero exit into success',async t=>{const d=fixture(t),r=await run(d,'console.log("PASS");process.exit(7)');assert.equal(r.status,'failed');assert.equal(r.exitCode,7);assert.equal(verifyReceipt(r,d).ok,false);});
test('missing executable is blocked, not passing',async t=>{const d=fixture(t),r=await runCheck({repo:d,id:'missing',argv:['jordan-no-such-command-xyz']});assert.equal(r.status,'blocked');assert.equal(r.spawnError,'ENOENT');});
test('timeout is a terminal nonpassing result',async t=>{const d=fixture(t),r=await run(d,'setInterval(()=>{},1000)',{timeoutMs:150});assert.equal(r.status,'timed-out');assert.ok(r.durationMs<5000);});
test('a successful command that edits source invalidates its receipt',async t=>{const d=fixture(t),r=await run(d,'require("node:fs").writeFileSync("value.txt","changed")');assert.equal(r.exitCode,0);assert.equal(r.status,'invalidated');assert.equal(r.stateChanged,true);});
test('receipts become stale after subsequent source edits',async t=>{const d=fixture(t),r=await run(d,'process.exit(0)');writeFileSync(join(d,'value.txt'),'later');assert.equal(verifyReceipt(r,d).ok,false);});
test('output collection is bounded and hashes the complete stream',async t=>{const d=fixture(t),r=await run(d,'process.stdout.write("a".repeat(1000))',{outputLimit:16});assert.equal(r.stdout.text.length,16);assert.equal(r.stdout.bytes,1000);assert.equal(r.stdout.truncated,true);assert.equal(r.stdout.sha256,createHash('sha256').update('a'.repeat(1000)).digest('hex'));});
test('command arguments are not interpreted by a shell',async t=>{const d=fixture(t),arg='literal; touch should-not-exist';const r=await runCheck({repo:d,id:'literal',argv:[process.execPath,'-e','process.stdout.write(process.argv[1])',arg]});assert.equal(r.stdout.text,arg);assert.equal(existsSync(join(d,'should-not-exist')),false);});
test('unsafe and malformed runner invocations fail before spawn',async t=>{const d=fixture(t);await assert.rejects(()=>runCheck({repo:d,id:'bad',argv:[],timeoutMs:1}));await assert.rejects(()=>runCheck({repo:d,id:'bad',argv:['node','\0']}));});
test('unresolved debugging example is valid but not marked fixed',()=>{const r=validateDebug(sample('debug'));assert.equal(r.ok,true);assert.match(r.evidenceAuthenticity,/not verified/);});
test('blocked reproduction cannot be relabeled a confirmed fix',()=>{const d=sample('debug');d.reproduction.status='blocked';d.conclusion='fixed';assert.equal(validateDebug(d).ok,false);});
test('fixed diagnosis needs a supported hypothesis and the original check',()=>{const d=sample('debug');d.conclusion='fixed';d.selectedHypothesis='stale-response';d.reproduction={...d.reproduction,status:'failed',evidence:['before.json']};d.experiments=[{hypothesisId:'stale-response',observation:'Obsolete request was accepted',result:'supports',evidence:['trace.json']}];d.verification={checkId:'search-order',status:'passed',evidence:['after.json']};d.regressionEvidence=['regression.json'];assert.equal(validateDebug(d).ok,true);d.verification.checkId='unrelated-test';assert.equal(validateDebug(d).ok,false);});
test('malformed debug experiment data is rejected, not dereferenced',()=>{const d=sample('debug');d.experiments={};assert.equal(validateDebug(d).ok,false);});
test('test matrix ties each case to a requirement and independent oracle',()=>{assert.equal(validateTestDesign(sample('test-design')).ok,true);});
test('uncovered requirements are rejected',()=>{const d=sample('test-design');d.requirements.push({id:'owner','expect':'Owner cannot change'});assert.equal(validateTestDesign(d).ok,false);});
test('missing oracle and forbidden-effect fields are rejected',()=>{const d=sample('test-design');delete d.cases[0].oracle;delete d.cases[0].forbiddenEffects;assert.equal(validateTestDesign(d).ok,false);});
test('not-tested UI template remains a partial review',()=>{assert.equal(validateInterface(sample('interface')).ok,true);});
test('untested interaction cannot become a complete UI review',()=>{const d=sample('interface');d.conclusion='complete';assert.equal(validateInterface(d).ok,false);});
test('missing keyboard review cannot be hidden from the report',()=>{const d=sample('interface');d.checks=d.checks.filter(c=>c.id!=='keyboard');assert.equal(validateInterface(d).ok,false);});
test('passing observations require evidence references',()=>{const d=sample('interface');d.checks[0].status='passed';assert.equal(validateInterface(d).ok,false);});
test('invalid input documents fail without throwing',()=>{for(const fn of [validateDebug,validateTestDesign,validateInterface])for(const v of [null,{},[]])assert.equal(fn(v).ok,false);});
test('CLI returns nonzero for invalid plans and unknown commands',()=>{const cli=join(root,'tools/skillcheck.mjs');let r=spawnSync(process.execPath,[cli,'not-a-command'],{encoding:'utf8'});assert.equal(r.status,2);r=spawnSync(process.execPath,[cli,'plan',join(root,'examples/skillcheck/plan.json')],{encoding:'utf8'});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).ok,true);});
test('controlled async and expiry probes detect three seeded defects',()=>{const r=spawnSync(process.execPath,[join(root,'examples/skillcheck/defect-demo.mjs')],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const report=JSON.parse(r.stdout);assert.equal(report.seededFailuresDetected,3);assert.equal(report.correctedPasses,6);});
