from pathlib import Path
import json
r=Path(__file__).resolve().parent.parent
sources={
 'vercel':{'title':'Vercel Agent Skills','repo':'vercel-labs/agent-skills','revision':'063bee94c3f4df8453406c830b0a7df0f2860278','author':'Vercel','archiveSha256':'3d11926496b220075c3e9ad57b42deef5d3f7a35c8253719c2059d18ad1a3b35','license':'MIT declared upstream; linked only','licensePath':None},
 'ecc':{'title':'ECC','repo':'affaan-m/ECC','revision':'dd6ee538aee0f548d4a6b520118f875431fd749e','author':'Affaan Mustafa and ECC contributors','archiveSha256':'d953919fb7dfd11633e3fff833735a243aadb2222bec1e7bbeeb44c47794c13a','license':'MIT','licensePath':'LICENSE'},
 'superpowers':{'title':'Superpowers','repo':'obra/superpowers','revision':'b36e0829c6d0140e93cfef2ca599b1b07d4a7797','author':'Jesse Vincent and Superpowers contributors','archiveSha256':'7c3ae7db406f8d92cf55329aa9e9a41e53f6cef00bdb68e1325713be97ef5d7c','license':'MIT','licensePath':'LICENSE'},
 'anthropic':{'title':'Anthropic Skills','repo':'anthropics/skills','revision':'34040c9c568585f6929bedeaad110ad08f079624','author':'Anthropic','archiveSha256':'94527d9bf3b49a8951aba1ce9420a37079f1a6677accca4b04435c79aabbe5bb','license':'Per-package; see each entry','licensePath':None},
 'supabase':{'title':'Supabase Agent Skills','repo':'supabase/agent-skills','revision':'8331f910845103c08d51f6ca1d86ebb7d1f745e3','author':'Supabase','archiveSha256':'f92f816eb578717e77a3b10d6b38a0e9ccad233c09fb83e0ff3cfd865b2e0a78','license':'MIT','licensePath':'LICENSE'}
}
(r/'catalog/upstreams.json').write_text(json.dumps(sources,indent=2)+'\n')
old=json.loads((r/'catalog/entries.json').read_text())
for e in old:
 if e['id'] in ['vercel-agent-skills','ecc','superpowers']:
  e['listed']=False
  e['sourceId']={'vercel-agent-skills':'vercel','ecc':'ecc','superpowers':'superpowers'}[e['id']]
 e['why']=e['outcome'] if e['origin']=='original' else {'skills-cli':'Reuse an existing selective installer instead of creating another package manager.','nx':'Keep workspace discovery and affected-task analysis close to the actual project graph.','playwright-mcp':'Give agents a structured browser tool surface when MCP fits the host.'}.get(e['id'],'The upstream collection is a source for the individual selections in this catalog.')
 if e['origin']=='original':e['author']='Jordan’s toolkit contributors (AI-assisted starters)'
def skill(provider,name,title,category,description,why,note,requires=(),mirror=True):
 s=sources[provider];path='skills/'+name
 e={'id':provider+'-'+name,'title':title,'description':description,'kind':'skill','origin':'curated','stage':'reference','category':category,'sourceId':provider,'upstreamPath':path,'url':f"https://github.com/{s['repo']}/blob/{s['revision']}/{path}/SKILL.md",'author':s['author'],'why':why,'note':note,'requires':list(requires),'outcome':description,'testedHosts':[],'evidence':[],'review':'Source reviewed; not host-tested','license':('Apache-2.0' if provider=='anthropic' else s['license']) if mirror else 'See upstream terms'}
 if mirror:e['vendorPath']=f'vendor/{provider}/{name}';e['packageLicense']=s['licensePath'] or path+'/LICENSE.txt'
 return e
new=[
 skill('vercel','react-best-practices','React Best Practices','Frontend','React and Next.js guidance for waterfalls, bundles, rendering, and data fetching.','A focused performance reference with individual rules and concrete code examples.','Use only with the matching React/Next.js versions. Linked upstream, not copied; this snapshot has an MIT declaration but no standalone repository license file.', ['React or Next.js'],False),
 skill('vercel','composition-patterns','React Composition Patterns','Frontend','Design flexible component APIs with compound components, lifted state, and composition.','Targets the component-design decisions that become painful as a UI library grows.','The React 19 section does not apply to React 18. Linked upstream; use the full package with its rules.', ['React'],False),
 skill('anthropic','frontend-design','Frontend Design','Frontend','Develop an intentional visual direction, typography, and layout for a specific product.','Complements code-quality skills with a deliberate design process rather than a generic UI template.','Upstream design guidance is opinionated. The actual brief and existing design system still control the work.'),
 skill('vercel','web-design-guidelines','Web Interface Review','Frontend','Review interface code against accessibility, interaction, navigation, and usability guidelines.','Adds a review pass for the details a successful build cannot catch.','Fetches a separate live guideline document. Pinning this skill does not pin that remote document; this is not an accessibility certification.', ['Web retrieval','UI source files'],False),
 skill('ecc','search-first','Search Before You Build','Planning','Compare existing packages, patterns, and tools before writing a custom implementation.','Makes adopt, extend, and build an explicit decision instead of defaulting to more code.','Search channels and researcher-agent names depend on the host. Upstream package examples still need verification.', ['Repository search','Relevant public documentation']),
 skill('superpowers','systematic-debugging','Systematic Debugging','Testing & quality','Investigate root causes, test hypotheses, and verify a fix before changing more code.','A disciplined alternative to speculative patches, with supporting debugging techniques in the package.','References other Superpowers skills that are not all bundled here. Helper scripts are copied as source and have not been executed.', ['A reproducible failure']),
 skill('ecc','tdd-workflow','Test-Driven Development','Testing & quality','Turn planned behavior into RED/GREEN test evidence and a reviewable implementation.','Connects the plan, the tests, and the implementation instead of treating test coverage as an afterthought.','Coverage targets and example commands are upstream conventions, not this collection’s guarantees. Use project-owned validation and approval rules.', ['Project test runner']),
 skill('anthropic','webapp-testing','Web App Testing','Testing & quality','Exercise local web applications with Playwright, screenshots, console logs, and server helpers.','Provides concrete browser-testing examples rather than stopping at a compiler or build check.','Includes Python helper scripts and examples. Review them before execution; do not treat upstream black-box advice as a reason to skip source review.', ['Python','Playwright','A local application']),
 skill('ecc','verification-loop','Verification Loop','Testing & quality','Review build, types, lint, tests, security checks, and the final diff before handoff.','A broad completion checklist that is useful after a cross-cutting change.','Full verification can be expensive. Adapt it to actual project commands; not every check applies to every edit.', ['Project-owned check commands']),
 skill('superpowers','verification-before-completion','Evidence Before Completion','Testing & quality','Require fresh command output before claiming a change is fixed, passing, or complete.','Addresses unsupported completion claims independently of the particular test framework.','Instructions do not enforce a security or CI boundary. Keep claims scoped to the checks actually executed.', ['Executable validation commands']),
 skill('superpowers','using-git-worktrees','Working in Git Worktrees','Parallel engineering','Detect existing workspace isolation and establish an owned worktree when needed.','Useful for avoiding branch collisions when engineering tasks run concurrently.','A worktree is not an OS sandbox. Setup commands must respect the repository’s package manager and permissions.', ['Git','Repository access']),
 skill('ecc','api-design','API Design','Backend & APIs','Review REST resources, HTTP semantics, pagination, errors, versioning, and rate limits.','A practical checklist for consistent public APIs and integration boundaries.','These are design conventions and examples, not a substitute for an executable API contract.', ['API requirements or an existing contract']),
 skill('ecc','golang-patterns','Go Development Patterns','Backend & APIs','Use idiomatic Go error handling, interfaces, concurrency, and package structure.','A language-specific companion to general agent instructions for backend engineering.','Review examples against the consuming project’s Go version and constraints.', ['Go source or a Go project']),
 skill('ecc','golang-testing','Go Testing Patterns','Testing & quality','Write table-driven tests, subtests, benchmarks, fuzz tests, and coverage checks in Go.','Adds concrete language-specific testing patterns beyond a generic TDD prompt.','Example tool versions and coverage thresholds are not automatically appropriate for a new project.', ['Go','Project test fixtures']),
 skill('supabase','supabase-postgres-best-practices','Postgres Best Practices','Databases','Review SQL, indexing, connection management, schema design, locking, and row-level security.','Brings database-specific guidance and detailed reference files into the same collection as application skills.','Some guidance is Supabase-specific. Example performance figures are not benchmarks from Jordan’s environment.', ['PostgreSQL context','Permission for any database access']),
 skill('anthropic','doc-coauthoring','Document Co-Authoring','Writing & docs','Structure technical documents through context gathering, refinement, and reader testing.','A useful companion for the articles and technical specifications that explain engineering work.','Linked only: no package-level license file was present in this snapshot. Do not infer redistribution terms from neighboring skills.', [],False)
]
entries=new+[e for e in old if e['kind']=='tool']+[e for e in old if e['origin']=='original']+[e for e in old if e.get('listed') is False]
flows={'ecc-search-first','ecc-tdd-workflow','ecc-verification-loop','superpowers-systematic-debugging','superpowers-verification-before-completion','superpowers-using-git-worktrees','anthropic-doc-coauthoring'}
for e in entries:
 if e['id'] in flows:e['kind']='workflow'
(r/'catalog/entries.json').write_text(json.dumps(entries,indent=2,ensure_ascii=False)+'\n')
